fix function names

diff --git a/bin/cleanFilenames b/bin/cleanFilenames
--- a/bin/cleanFilenames
+++ b/bin/cleanFilenames
@@ -2,9 +2,9 @@
 
 version="1.1.0"
 
-function _mainScript_() {
+_mainScript_() {
 
-  function _errorHandling_() {
+  _errorHandling_() {
     # This script requires the Linux gdate (as opposed to native 'date' in OSX)
     # Here we see if it's installed. If not, we install it with homebrew.
     if ! command -v gdate &> /dev/null; then
@@ -16,7 +16,7 @@ function _mainScript_() {
   }
   _errorHandling_
 
-  function _createTestFiles_() {
+  _createTestFiles_() {
     filenamesForTesting=(
       "2016-01-01 Already datestamped.txt"
       "YYY MM DD 2016 03 19 file.txt"
@@ -37,19 +37,14 @@ function _mainScript_() {
       )
     notice "Creating test files..."
     for testFile in "${filenamesForTesting[@]}"; do
-      if ${dryrun}; then
-        info "Would have created: '$testFile'"
-      else
-        touch "${testFile}"
-        verbose "creating: '$testFile'"
-    fi
+      _execute_ "touch \"${testFile}\""
     done
     success "Test files created"
     _safeExit_
   }
   if "${createTestFiles}"; then _createTestFiles_; fi
 
-  function realpath() {
+  realpath() {
     # Convert a relative path to an absolute path.
     #
     # From http://github.com/morgant/realpath
@@ -113,7 +108,7 @@ function _mainScript_() {
     ${successPath}
   }
 
-  function _isGoodFile_() {
+  _isGoodFile_() {
 
     #Bypass file check when testing input
     if $testOutput; then return 0; fi
@@ -148,7 +143,7 @@ function _mainScript_() {
     return 0
   }
 
-  function _parseFilename_() {
+  _parseFilename_() {
     # Here we parse the user's file into it's directory, basename, and extension.
 
     # Grab the directory
@@ -167,7 +162,7 @@ function _mainScript_() {
     originalFileWithPath="${filePath}${userFile}"
   }
 
-  function _clean_() {
+  _clean_() {
     # This function attempts to clean common (or less common) Filename issues.
     local string="$1"
 
@@ -188,7 +183,7 @@ function _mainScript_() {
     echo "$string"
   }
 
-  function _findDate_() {
+  _findDate_() {
     # This function parses file names looking for a date in a recognizable format.
     # When a date is found we normalize it into YYYY-MM-DD format. If no date is found,
     # we add one.
@@ -324,7 +319,7 @@ function _mainScript_() {
     fi
   }
 
-  function _changeFilename_() {
+  _changeFilename_() {
     local regex="$1"
     local dateCommand="$2"
 
@@ -347,7 +342,7 @@ function _mainScript_() {
     verbose "\t origdate: $origDate newDate: $newDate"
   }
 
-  function _rebuildFileName_() {
+  _rebuildFileName_() {
     # piece the filename back together
 
     # Ensure file extensions are lowercase
@@ -365,7 +360,7 @@ function _mainScript_() {
     newFilename="${baseFilename}.${extension}"
   }
 
-  function _renameFiles_() {
+  _renameFiles_() {
     # Renames the files. If the new Filename exists, we keep incrementing
     # a number to append to the Filename to mimic Finder
 
@@ -376,7 +371,7 @@ function _mainScript_() {
     fi
 
     if [ ! -e "${newFilename}" ]; then
-      execute "mv '${originalFileWithPath}' '${filePath}${newFilename}'" "${userFile} --> ${newFilename}"
+      _execute_ "mv \"${originalFileWithPath}\" \"${filePath}${newFilename}\"" "${userFile} --> ${newFilename}"
     else
       local i=2
       newFilename="${baseFilename} ${i}.${extension}"
@@ -384,7 +379,7 @@ function _mainScript_() {
         ((i=i+1))
         newFilename="${baseFilename} ${i}.${extension}"
       done
-      execute "mv '${originalFileWithPath}' '${filePath}${newFilename}'" "${userFile} --> ${newFilename}"
+      _execute_ "mv \"${originalFileWithPath}\" \"${filePath}${newFilename}\"" "${userFile} --> ${newFilename}"
     fi
   }
 
@@ -407,12 +402,12 @@ function _mainScript_() {
 
 } # end _mainScript_
 
-function _trapCleanup_() {
+_trapCleanup_() {
   echo ""
   die "Exit trapped. In function: '${FUNCNAME[*]:1}'"
 }
 
-function _safeExit_() {
+_safeExit_() {
   trap - INT TERM EXIT
   exit ${1:-0}
 }
@@ -430,8 +425,6 @@ cleanOnly=false;  nonInteractive=false; lowerCase=false;
 ignoreFile=false; removeDates=false;    createTestFiles=false;
 testOutput=false;
 
-
-
 # Set Colors
 bold=$(tput bold);        reset=$(tput sgr0);         purple=$(tput setaf 171);
 red=$(tput setaf 1);      green=$(tput setaf 76);      tan=$(tput setaf 3);
@@ -440,7 +433,7 @@ blue=$(tput setaf 38);    underline=$(tput sgr 0 1);
 # Logging & Feedback
 logFile="${HOME}/Library/Logs/${scriptName%.sh}.log"
 
-function _alert_() {
+_alert_() {
   if [ "${1}" = "error" ]; then local color="${bold}${red}"; fi
   if [ "${1}" = "warning" ]; then local color="${red}"; fi
   if [ "${1}" = "success" ]; then local color="${green}"; fi
@@ -611,40 +604,18 @@ done
 # Store the remaining part as arguments.
 args+=("$@")
 
-
-function seek_confirmation() {
-  # Seeks a Yes or No answer to a question.  Usage:
-  #   if seek_confirmation "Answer this question"; then
-  #     something
-  #   fi
-  input "$@"
-  if "${force}"; then
-    verbose "Forcing confirmation with '--force' flag set"
-    return 0
-  else
-    while true; do
-      read -r -p " (y/n) " yn
-      case $yn in
-        [Yy]* ) return 0;;
-        [Nn]* ) return 1;;
-        * ) input "Please answer yes or no.";;
-      esac
-    done
-  fi
-}
-
-function execute() {
-  # execute - wrap an external command in 'execute' to push native output to /dev/null
+_execute_() {
+  # _execute_ - wrap an external command in '_execute_' to push native output to /dev/null
   #           and have control over the display of the results.  In "dryrun" mode these
   #           commands are not executed at all. In Verbose mode, the commands are executed
   #           with results printed to stderr and stdin
   #
   # usage:
-  #   execute "cp -R somefile.txt someNewFile.txt" "Optional message to print to user"
+  #   _execute_ "cp -R \"~/dir/somefile.txt\" \"someNewFile.txt\"" "Optional message to print to user"
   if ${dryrun}; then
     dryrun "${2:-$1}"
   else
-    #set +e # don't exit script if execute fails
+    set +e # don't exit script if execute fails
     if $verbose; then
       eval "$1"
     else
@@ -655,7 +626,7 @@ function execute() {
     else
       warning "${2:-$1}"
     fi
-    # set -e
+    set -e
   fi
 }
 
@@ -666,7 +637,7 @@ trap _trapCleanup_ EXIT INT TERM
 IFS=$' \n\t'
 
 # Exit on error. Append '||true' when you run the script if you expect an error.
-# if using the 'execute' function this must be disabled for warnings to be shown if tasks fail
+# if using the '_execute_' function this must be disabled for warnings to be shown if tasks fail
 #set -o errexit
 
 # Run in debug mode, if set
diff --git a/bin/removeSymlink b/bin/removeSymlink
--- a/bin/removeSymlink
+++ b/bin/removeSymlink
@@ -2,9 +2,9 @@
 
 version="1.2.0"
 
-function _mainScript_() {
+_mainScript_() {
 
-  function _errorHandling_() {
+  _errorHandling_() {
     # This script requires the Linux gdate (as opposed to native 'date' in OSX)
     # Here we see if it's installed. If not, we install it with homebrew.
     if ! command -v dirname &> /dev/null; then
@@ -34,25 +34,25 @@ function _mainScript_() {
     esac
     [ -e "${abstarget}" ] || die "Can not find original file."
 
-    execute "rm -f \"${link}\""
-    execute "cp -rf \"${abstarget}\" \"${link}\""
+    _execute_ "rm -f \"${link}\""
+    _execute_ "cp -rf \"${abstarget}\" \"${link}\""
 
     # If requested, remove the originating file
     if ${replaceSymlink}; then
-      if seek_confirmation "Delete originating file?"; then
-        execute "rm -rf \"${abstarget}\""
+      if _seekConfirmation_ "Delete originating file?"; then
+        _execute_ "rm -rf \"${abstarget}\""
       fi
     fi
   done
 
 }
 
-function _trapCleanup_() {
+_trapCleanup_() {
   echo ""
   die "Exit trapped. In function: '${FUNCNAME[*]:1}'"
 }
 
-function _safeExit_() {
+_safeExit_() {
   trap - INT TERM EXIT
   exit ${1:-0}
 }
@@ -73,7 +73,7 @@ bold=$(tput bold);        reset=$(tput sgr0);         purple=$(tput setaf 171);
 red=$(tput setaf 1);      green=$(tput setaf 76);      tan=$(tput setaf 3);
 blue=$(tput setaf 38);    underline=$(tput sgr 0 1);
 
-function _alert_() {
+_alert_() {
   if [ "${1}" = "error" ]; then local color="${bold}${red}"; fi
   if [ "${1}" = "warning" ]; then local color="${red}"; fi
   if [ "${1}" = "success" ]; then local color="${green}"; fi
@@ -189,9 +189,9 @@ done
 # Store the remaining part as arguments.
 args+=("$@")
 
-function seek_confirmation() {
+_seekConfirmation_() {
   # Seeks a Yes or No answer to a question.  Usage:
-  #   if seek_confirmation "Answer this question"; then
+  #   if _seekConfirmation_ "Answer this question"; then
   #     something
   #   fi
   input "$@"
@@ -205,18 +205,18 @@ function seek_confirmation() {
   done
 }
 
-function execute() {
-  # execute - wrap an external command in 'execute' to push native output to /dev/null
+_execute_() {
+  # _execute_ - wrap an external command in '_execute_' to push native output to /dev/null
   #           and have control over the display of the results.  In "dryrun" mode these
   #           commands are not executed at all. In Verbose mode, the commands are executed
   #           with results printed to stderr and stdin
   #
   # usage:
-  #   execute "cp -R somefile.txt someNewFile.txt" "Optional message to print to user"
+  #   _execute_ "cp -R \"~/dir/somefile.txt\" \"someNewFile.txt\"" "Optional message to print to user"
   if ${dryrun}; then
     dryrun "${2:-$1}"
   else
-    set +e # don't exit script if execute fails
+    #set +e # don't exit script if execute fails
     if $verbose; then
       eval "$1"
     else
@@ -227,7 +227,7 @@ function execute() {
     else
       warning "${2:-$1}"
     fi
-    set -e
+    # set -e
   fi
 }
 
