Format with shfmt

diff --git a/bin/cleanFilenames b/bin/cleanFilenames
--- a/bin/cleanFilenames
+++ b/bin/cleanFilenames
@@ -8,8 +8,8 @@ _mainScript_() {
     # This script requires the Linux gdate (as opposed to native 'date' in OSX)
     # Here we see if it's installed. If not, we install it with homebrew.
     if [[ "$OSTYPE" =~ darwin* ]]; then
-      if ! command -v gdate &> /dev/null; then
-        if command -v brew &> /dev/null; then
+      if ! command -v gdate &>/dev/null; then
+        if command -v brew &>/dev/null; then
           warning "Need 'gdate' to continue. Installing via homebrew."
           brew install coreutils
           notice "'coreutils' package installed. Exiting."
@@ -25,7 +25,7 @@ _mainScript_() {
   _isGoodFile_() {
 
     #Bypass file check when testing input
-    ( $testOutput ) && return 0
+    ($testOutput) && return 0
 
     # Ensure file exists
     if [ ! -e "${userFile}" ]; then
@@ -118,114 +118,114 @@ _mainScript_() {
     if "${cleanOnly}"; then return; fi
 
     #Match "YYYY-MM-DD in Filename"
-      regex="[0-9]{4}[_ -][0-9]{2}[_ -][0-9]{2}"
-      if [[ "${baseFilename}" =~ ${regex} ]]; then
-        verbose "\t match: YYYY-MM-DD"
-        dateCommand="awk -v FS=- -v OFS=- '{print \$1,\$2,\$3}'"
-        _changeFilename_ "$regex" "$dateCommand"
-        return
-      fi
+    regex="[0-9]{4}[_ -][0-9]{2}[_ -][0-9]{2}"
+    if [[ "${baseFilename}" =~ ${regex} ]]; then
+      verbose "\t match: YYYY-MM-DD"
+      dateCommand="awk -v FS=- -v OFS=- '{print \$1,\$2,\$3}'"
+      _changeFilename_ "$regex" "$dateCommand"
+      return
+    fi
 
     #Match "MM-DD-YYYY in Filename"
-      regex="[0-9]{2}[_ -][0-9]{2}[_ -][0-9]{4}"
-      if [[ "${baseFilename}" =~ ${regex} ]]; then
-        verbose "\t match: MM-DD-YYYY"
-        dateCommand="awk -v FS=- -v OFS=- '{print \$3,\$1,\$2}'"
-        _changeFilename_ "$regex" "$dateCommand"
-        return
-      fi
+    regex="[0-9]{2}[_ -][0-9]{2}[_ -][0-9]{4}"
+    if [[ "${baseFilename}" =~ ${regex} ]]; then
+      verbose "\t match: MM-DD-YYYY"
+      dateCommand="awk -v FS=- -v OFS=- '{print \$3,\$1,\$2}'"
+      _changeFilename_ "$regex" "$dateCommand"
+      return
+    fi
 
     # Match "MMDDYYYY or YYYYMMDD in Filename"
-      regex='(^|[[:space:]]|-)[0-9]{8}($|[[:space:]]|-)'
-      if [[ "${baseFilename}" =~ $regex ]]; then
-        yearRegex="(^|[[:space:]]|-)20[0-9][0-9][0-9][0-9][0-9][0-9]"
-        regex="[0-9]{8}"
-        if [[ "${baseFilename}" =~ ${yearRegex} ]]; then
-          verbose "\t match: YYYYMMDD"
-          dateCommand="sed -E 's/([0-9]{4})([0-9]{2})([0-9]{2})/\1-\2-\3/g' | awk -v FS=- -v OFS=- '{print \$1,\$2,\$3}'"
-        else
-          verbose "\t match: MMDDYYYY"
-          dateCommand="sed -E 's/([0-9]{2})([0-9]{2})([0-9]{4})/\1-\2-\3/g' | awk -v FS=- -v OFS=- '{print \$3,\$1,\$2}'"
-        fi
-        _changeFilename_ "$regex" "$dateCommand"
-        return
+    regex='(^|[[:space:]]|-)[0-9]{8}($|[[:space:]]|-)'
+    if [[ "${baseFilename}" =~ $regex ]]; then
+      yearRegex="(^|[[:space:]]|-)20[0-9][0-9][0-9][0-9][0-9][0-9]"
+      regex="[0-9]{8}"
+      if [[ "${baseFilename}" =~ ${yearRegex} ]]; then
+        verbose "\t match: YYYYMMDD"
+        dateCommand="sed -E 's/([0-9]{4})([0-9]{2})([0-9]{2})/\1-\2-\3/g' | awk -v FS=- -v OFS=- '{print \$1,\$2,\$3}'"
+      else
+        verbose "\t match: MMDDYYYY"
+        dateCommand="sed -E 's/([0-9]{2})([0-9]{2})([0-9]{4})/\1-\2-\3/g' | awk -v FS=- -v OFS=- '{print \$3,\$1,\$2}'"
       fi
+      _changeFilename_ "$regex" "$dateCommand"
+      return
+    fi
 
     # Match "MMDDYY or YYMMDD in Filename"
-      regex="(^|[[:space:]]|-)[0-9]{6}($|[[:space:]]|-)"
-      if [[ "${baseFilename}" =~ ${regex} ]]; then
-        yearRegex="1[3-9][0-9]{4}"
-        regex="[0-9]{6}"
-        if [[ "${baseFilename}" =~ ${yearRegex} ]]; then
-          verbose "\t match: YYMMDD"
-          dateCommand="sed -E 's/([0-9]{2})([0-9]{2})([0-9]{2})/20\1-\2-\3/g' | awk -v FS=- -v OFS=- '{print \$1,\$2,\$3}'"
-        else
-          verbose "\t match: MMDDYY"
-          dateCommand="sed -E 's/([0-9]{2})([0-9]{2})([0-9]{2})/\1-\2-20\3/g' | awk -v FS=- -v OFS=- '{print \$3,\$1,\$2}'"
-        fi
-        _changeFilename_ "$regex" "$dateCommand"
-        return
+    regex="(^|[[:space:]]|-)[0-9]{6}($|[[:space:]]|-)"
+    if [[ "${baseFilename}" =~ ${regex} ]]; then
+      yearRegex="1[3-9][0-9]{4}"
+      regex="[0-9]{6}"
+      if [[ "${baseFilename}" =~ ${yearRegex} ]]; then
+        verbose "\t match: YYMMDD"
+        dateCommand="sed -E 's/([0-9]{2})([0-9]{2})([0-9]{2})/20\1-\2-\3/g' | awk -v FS=- -v OFS=- '{print \$1,\$2,\$3}'"
+      else
+        verbose "\t match: MMDDYY"
+        dateCommand="sed -E 's/([0-9]{2})([0-9]{2})([0-9]{2})/\1-\2-20\3/g' | awk -v FS=- -v OFS=- '{print \$3,\$1,\$2}'"
       fi
+      _changeFilename_ "$regex" "$dateCommand"
+      return
+    fi
 
     # Match "MM-DD-YY or YY-MM-DD  in Filename"
-      regex="[0-9]{2}[_ -][0-9]{2}[_ -][0-9]{2}"
-      if [[ "${baseFilename}" =~ ${regex} ]]; then
-        yearRegex="1[3-9][_ -][0-9][0-9][_ -][0-9][0-9]"
-        if [[ "${baseFilename}" =~ ${yearRegex} ]]; then
-          verbose "\t match: YY-MM-DD"
-          dateCommand="awk -v FS=- -v OFS=- '{print 20\$1,\$2,\$3}'"
-        else
-          verbose "\t match: MM-DD-YY"
-          dateCommand="awk -v FS=- -v OFS=- '{print 20\$3,\$1,\$2}'"
-        fi
-        _changeFilename_ "$regex" "$dateCommand"
-        return
+    regex="[0-9]{2}[_ -][0-9]{2}[_ -][0-9]{2}"
+    if [[ "${baseFilename}" =~ ${regex} ]]; then
+      yearRegex="1[3-9][_ -][0-9][0-9][_ -][0-9][0-9]"
+      if [[ "${baseFilename}" =~ ${yearRegex} ]]; then
+        verbose "\t match: YY-MM-DD"
+        dateCommand="awk -v FS=- -v OFS=- '{print 20\$1,\$2,\$3}'"
+      else
+        verbose "\t match: MM-DD-YY"
+        dateCommand="awk -v FS=- -v OFS=- '{print 20\$3,\$1,\$2}'"
       fi
+      _changeFilename_ "$regex" "$dateCommand"
+      return
+    fi
 
     # Match "M DD YY in Filename"
-      regex="[0-9]{1}[_ -][0-9]{2}[_ -][0-9]{2}"
-      if [[ "${baseFilename}" =~ ${regex} ]]; then
-        verbose "\t match: M DD YY "
-        dateCommand="sed -E 's/([0-9])[_ -]([0-9]{2})[_ -]([0-9]{2})/0\1-\2-20\3/g' | awk -v FS=- -v OFS=- '{print \$3,\$1,\$2}'"
-        _changeFilename_ "$regex" "$dateCommand"
-        return
-      fi
+    regex="[0-9]{1}[_ -][0-9]{2}[_ -][0-9]{2}"
+    if [[ "${baseFilename}" =~ ${regex} ]]; then
+      verbose "\t match: M DD YY "
+      dateCommand="sed -E 's/([0-9])[_ -]([0-9]{2})[_ -]([0-9]{2})/0\1-\2-20\3/g' | awk -v FS=- -v OFS=- '{print \$3,\$1,\$2}'"
+      _changeFilename_ "$regex" "$dateCommand"
+      return
+    fi
 
     # Match "M D YY in Filename"
-      regex="[0-9][_ -][0-9][_ -][0-9][0-9]"
-      if [[ "${baseFilename}" =~ ${regex} ]]; then
-        verbose "\t match: M D YY "
-        dateCommand="sed -E 's/([0-9])[_ -]([0-9])[_ -]([0-9]{2})/0\1-0\2-20\3/g' | awk -v FS=- -v OFS=- '{print \$3,\$1,\$2}'"
-        _changeFilename_ "$regex" "$dateCommand"
-        return
-      fi
+    regex="[0-9][_ -][0-9][_ -][0-9][0-9]"
+    if [[ "${baseFilename}" =~ ${regex} ]]; then
+      verbose "\t match: M D YY "
+      dateCommand="sed -E 's/([0-9])[_ -]([0-9])[_ -]([0-9]{2})/0\1-0\2-20\3/g' | awk -v FS=- -v OFS=- '{print \$3,\$1,\$2}'"
+      _changeFilename_ "$regex" "$dateCommand"
+      return
+    fi
 
     # Match month-DD-YYYY
-      regex="([Jj](an|anuary)|[Ff](eb|ebruary)|[Mm](ar|arch)|[Aa](pr|pril)|[Mm]ay|[Jj](un|une)|[Jj](ul|uly)|[Aa](ug|ugust)|[Ss](ep|ept|eptember)|[Oo](ct|ctober)|[Nn](ov|ovember)|[Dd](ec|ecember))[_ -][0-9]{2}[_ -][0-9]{4}"
-      if [[ "${baseFilename}" =~ ${regex} ]]; then
-        verbose "\t match: Month-DD-YYYY"
-        dateCommand='{ read ddate ; gdate -d "$ddate" +%Y-%m-%d ; }'
-        _changeFilename_ "$regex" "$dateCommand"
-        return
-      fi
+    regex="([Jj](an|anuary)|[Ff](eb|ebruary)|[Mm](ar|arch)|[Aa](pr|pril)|[Mm]ay|[Jj](un|une)|[Jj](ul|uly)|[Aa](ug|ugust)|[Ss](ep|ept|eptember)|[Oo](ct|ctober)|[Nn](ov|ovember)|[Dd](ec|ecember))[_ -][0-9]{2}[_ -][0-9]{4}"
+    if [[ "${baseFilename}" =~ ${regex} ]]; then
+      verbose "\t match: Month-DD-YYYY"
+      dateCommand='{ read ddate ; gdate -d "$ddate" +%Y-%m-%d ; }'
+      _changeFilename_ "$regex" "$dateCommand"
+      return
+    fi
 
     # Match month-DD-YY
-      regex="([Jj](an|anuary)|[Ff](eb|ebruary)|[Mm](ar|arch)|[Aa](pr|pril)|[Mm]ay|[Jj](un|une)|[Jj](ul|uly)|[Aa](ug|ugust)|[Ss](ep|ept|eptember)|[Oo](ct|ctober)|[Nn](ov|ovember)|[Dd](ec|ecember))[_ -][0-9]{2}[_ -][0-9]{2}"
-      if [[ "${baseFilename}" =~ ${regex} ]]; then
-        verbose "\t match: Month-DD-YY"
-        dateCommand='awk -v FS=- -v OFS=- "{print \$1,\$2,20\$3}" | { read ddate ; gdate -d "$ddate" +%Y-%m-%d ; }'
-        _changeFilename_ "$regex" "$dateCommand"
-        return
-      fi
+    regex="([Jj](an|anuary)|[Ff](eb|ebruary)|[Mm](ar|arch)|[Aa](pr|pril)|[Mm]ay|[Jj](un|une)|[Jj](ul|uly)|[Aa](ug|ugust)|[Ss](ep|ept|eptember)|[Oo](ct|ctober)|[Nn](ov|ovember)|[Dd](ec|ecember))[_ -][0-9]{2}[_ -][0-9]{2}"
+    if [[ "${baseFilename}" =~ ${regex} ]]; then
+      verbose "\t match: Month-DD-YY"
+      dateCommand='awk -v FS=- -v OFS=- "{print \$1,\$2,20\$3}" | { read ddate ; gdate -d "$ddate" +%Y-%m-%d ; }'
+      _changeFilename_ "$regex" "$dateCommand"
+      return
+    fi
 
     # Match month-YYYY
-      regex="([Jj](an|anuary)|[Ff](eb|ebruary)|[Mm](ar|arch)|[Aa](pr|pril)|[Mm]ay|[Jj](un|une)|[Jj](ul|uly)|[Aa](ug|ugust)|[Ss](ep|ept|eptember)|[Oo](ct|ctober)|[Nn](ov|ovember)|[Dd](ec|ecember))[_ -][0-9]{4}"
-      if [[ "${baseFilename}" =~ ${regex} ]]; then
-        verbose "\t match: Month-YYYY"
-        dateCommand='echo "01 $origDate" | { read ddate ; gdate -d "$ddate" +%Y-%m-%d ; }'
-        _changeFilename_ "$regex" "$dateCommand"
-        return
-      fi
+    regex="([Jj](an|anuary)|[Ff](eb|ebruary)|[Mm](ar|arch)|[Aa](pr|pril)|[Mm]ay|[Jj](un|une)|[Jj](ul|uly)|[Aa](ug|ugust)|[Ss](ep|ept|eptember)|[Oo](ct|ctober)|[Nn](ov|ovember)|[Dd](ec|ecember))[_ -][0-9]{4}"
+    if [[ "${baseFilename}" =~ ${regex} ]]; then
+      verbose "\t match: Month-YYYY"
+      dateCommand='echo "01 $origDate" | { read ddate ; gdate -d "$ddate" +%Y-%m-%d ; }'
+      _changeFilename_ "$regex" "$dateCommand"
+      return
+    fi
 
     # Act on files which don't match known patterns
     verbose "\t No recognized date in filename. Using creation date or today"
@@ -233,12 +233,12 @@ _mainScript_() {
     # Add a date to files which don't already have one.
     # use mdls to find the creation date of the file. if it exists, use that. if not, use today
     if ${removeDates}; then return; fi # don't do this step if we are trying to remove dates
-    if mdls -raw -name kMDItemContentCreationDate "${originalFileWithPath}" &> /dev/null; then
+    if mdls -raw -name kMDItemContentCreationDate "${originalFileWithPath}" &>/dev/null; then
       creationDate=$(mdls -raw -name kMDItemContentCreationDate "${originalFileWithPath}")
       if [[ "$creationDate" =~ null ]]; then
         newDate="$(date +%Y-%m-%d)"
       else
-        newDate=$(echo "$creationDate" | awk 'BEGIN { FS="[ ]" } ; { print $1 }' )
+        newDate=$(echo "$creationDate" | awk 'BEGIN { FS="[ ]" } ; { print $1 }')
       fi
     else
       newDate="$(date +%Y-%m-%d)"
@@ -316,20 +316,23 @@ _mainScript_() {
       _findDate_
       _rebuildFileName_
       _renameFiles_
-      if ${nonInteractive}; then echo "${newFile}" ; fi
+      if ${nonInteractive}; then echo "${newFile}"; fi
     fi
   done
 
 } # end _mainScript_
 
 filesToSource=(
-  ${HOME}/dotfiles/scripting/helpers/baseHelpers.bash
-  ${HOME}/dotfiles/scripting/helpers/files.bash
+  "${HOME}/dotfiles/scripting/helpers/baseHelpers.bash"
+  "${HOME}/dotfiles/scripting/helpers/files.bash"
 )
 
 for sourceFile in "${filesToSource[@]}"; do
   [ ! -f "$sourceFile" ] \
-    &&  { echo "error: Can not find sourcefile '$sourceFile'. Exiting."; exit 1; }
+    && {
+      echo "error: Can not find sourcefile '$sourceFile'. Exiting."
+      exit 1
+    }
 
   source "$sourceFile"
 done
@@ -339,12 +342,23 @@ done
 scriptName=$(basename "$0")
 
 # Set Flags
-quiet=false;        printLog=false;            logErrors=true;    verbose=false;
-force=false;        strict=false;              dryrun=false;
-debug=false;        sourceOnly=false;          args=();
+quiet=false
+printLog=false
+logErrors=true
+verbose=false
+force=false
+strict=false
+dryrun=false
+debug=false
+sourceOnly=false
+args=()
 
-cleanOnly=false;    nonInteractive=false;       lowerCase=false;
-ignoreFile=false;   removeDates=false;          testOutput=false;
+cleanOnly=false
+nonInteractive=false
+lowerCase=false
+ignoreFile=false
+removeDates=false
+testOutput=false
 
 # Options and Usage
 # -----------------------------------
@@ -422,7 +436,7 @@ while (($#)); do
     # If option is of type -ab
     -[!-]?*)
       # Loop over each character starting with the second
-      for ((i=1; i < ${#1}; i++)); do
+      for ((i = 1; i < ${#1}; i++)); do
         c=${1:i:1}
 
         # Add current char to options
@@ -430,7 +444,7 @@ while (($#)); do
 
         # If option takes a required argument, and it's not the last char make
         # the rest of the string its argument
-        if [[ $optstring = *"$c:"* && ${1:i+1} ]]; then
+        if [[ $optstring == *"$c:"* && ${1:i+1} ]]; then
           options+=("${1:i+1}")
           break
         fi
@@ -455,24 +469,39 @@ unset options
 [[ $# -eq 0 ]] && set -- "--help"
 
 # Read the options and set stuff
-while [[ $1 = -?* ]]; do
+while [[ $1 == -?* ]]; do
   case $1 in
-    -C|--clean) cleanOnly=true ;;
-    -R| --removeDate) removeDates=true ;;
-    -L| --lower) lowerCase=true ;;
-    -e|--noErrorLog) logErrors=false ;;
-    -n|--dryrun) dryrun=true ;;
-    --nonInteractive) nonInteractive=true; quiet=true; ;;
-    -h|--help) _usage_ >&2 ; _safeExit_ ;;
-    -T|--test) testOutput=true; dryrun=true ;;
-    --version) echo "$(basename $0) ${version}"; _safeExit_ ;;
-    -v|--verbose) verbose=true ;;
-    -l|--log) printLog=true ;;
-    -q|--quiet) quiet=true ;;
-    -s|--strict) strict=true;;
-    -d|--debug) debug=true;;
-    --source-only) sourceOnly=true;;
-    --endopts) shift; break ;;
+    -C | --clean) cleanOnly=true ;;
+    -R | --removeDate) removeDates=true ;;
+    -L | --lower) lowerCase=true ;;
+    -e | --noErrorLog) logErrors=false ;;
+    -n | --dryrun) dryrun=true ;;
+    --nonInteractive)
+      nonInteractive=true
+      quiet=true
+      ;;
+    -h | --help)
+      _usage_ >&2
+      _safeExit_
+      ;;
+    -T | --test)
+      testOutput=true
+      dryrun=true
+      ;;
+    --version)
+      echo "$(basename $0) ${version}"
+      _safeExit_
+      ;;
+    -v | --verbose) verbose=true ;;
+    -l | --log) printLog=true ;;
+    -q | --quiet) quiet=true ;;
+    -s | --strict) strict=true ;;
+    -d | --debug) debug=true ;;
+    --source-only) sourceOnly=true ;;
+    --endopts)
+      shift
+      break
+      ;;
     *) die "invalid option: '$1'." ;;
   esac
   shift
@@ -494,13 +523,13 @@ IFS=$' \n\t'
 # set -o errtrace
 
 # Run in debug mode, if set
-if ${debug}; then set -x ; fi
+if ${debug}; then set -x; fi
 
 # Exit on empty variable
-if ${strict}; then set -o nounset ; fi
+if ${strict}; then set -o nounset; fi
 
 # Run your script unless in source only mode
-if ! ${sourceOnly}; then _mainScript_ ; fi
+if ! ${sourceOnly}; then _mainScript_; fi
 
 # Exit cleanly
-if ! ${sourceOnly}; then _safeExit_ ; fi
+if ! ${sourceOnly}; then _safeExit_; fi
diff --git a/bin/convertVideo b/bin/convertVideo
--- a/bin/convertVideo
+++ b/bin/convertVideo
@@ -2,7 +2,7 @@
 
 # ##################################################
 #
-version="1.0.0"              # Sets version variable
+version="1.0.0" # Sets version variable
 #
 # A script to convert video files from one format/size to another. In essence, this is
 # a wrapper for FFMPEG
@@ -29,7 +29,7 @@ _mainScript_() {
     http -d --body http://www.sample-videos.com/video/mkv/720/big_buck_bunny_720p_1mb.mkv
     http -d --body http://www.sample-videos.com/audio/mp3/india-national-anthem.mp3
     http -d --body http://samples.mplayerhq.hu/avi/imaadpcm.avi
-    if type -P youtube-dl &> /dev/null; then
+    if type -P youtube-dl &>/dev/null; then
       youtube-dl -f "[height <=? 720]" -o test-720p.mp4 https://www.youtube.com/watch?v=1-UdWS4RAA4
       youtube-dl -o test-1080p.mp4 https://www.youtube.com/watch?v=1-UdWS4RAA4
     fi
@@ -43,7 +43,7 @@ _mainScript_() {
     # Check for the necessary command line packages
     verbose "Checking dependencies..."
     for CLIDependency in "${CLIDependencies[@]}"; do
-      if ! command -v "${CLIDependency}" > /dev/null; then
+      if ! command -v "${CLIDependency}" >/dev/null; then
         die "We need '${CLIDependency}' to run. Please install..."
       fi
     done
@@ -60,9 +60,8 @@ _mainScript_() {
 
     [ ${#filesToConvert[@]} -eq 0 ] && die "Please specify at least one video file."
 
-
-   # Confirm that ffprobe works
-    if ! ffprobe -v quiet -print_format json -show_format -show_streams "${args[0]}" &> /dev/null; then
+    # Confirm that ffprobe works
+    if ! ffprobe -v quiet -print_format json -show_format -show_streams "${args[0]}" &>/dev/null; then
       die "Seems ffmpeg has a dependency problem"
     fi
 
@@ -81,12 +80,12 @@ _mainScript_() {
   _parseFileJson_() {
     # parseFileJson() Uses 'ffprobe' to gather all relevant information about a file in JSON format
 
-    local informationFile="${tmpDir}/${RANDOM}.${file////}.json"  # Create the temporary JSON file
+    local informationFile="${tmpDir}/${RANDOM}.${file////}.json" # Create the temporary JSON file
 
     # verbose "\t Reading audio data and writing JSON to tmp"
 
     # Output the JSON file
-    ffprobe -v quiet -print_format json -show_format -show_streams "${file}" >> "${informationFile}"
+    ffprobe -v quiet -print_format json -show_format -show_streams "${file}" >>"${informationFile}"
 
     # If the '--probe' flag is set, we print information to the screen and exit.
     if "${probe}"; then
@@ -103,14 +102,14 @@ _mainScript_() {
     # formatBit_Rate="$(jq -r ".format.bit_rate" "${informationFile}")"
     # numStreams="$(jq -r ".format.nb_streams" "${informationFile}")"
 
-    if jq -e '.streams[] | select(.codec_type=="video")' "${informationFile}" > /dev/null; then
+    if jq -e '.streams[] | select(.codec_type=="video")' "${informationFile}" >/dev/null; then
       videoHeight=$(jq -r '.streams[] | select(.codec_type=="video" and .codec_name!="mjpeg") | .height' "${informationFile}")
       videoWidth=$(jq -r '.streams[] | select(.codec_type=="video" and .codec_name!="mjpeg") | .width' "${informationFile}")
       videoCodec=$(jq -r '.streams[] | select(.codec_type=="video" and .codec_name!="mjpeg") | .codec_name' "${informationFile}")
       videoCodecLong=$(jq -r '.streams[] | select(.codec_type=="video" and .codec_name!="mjpeg") | .codec_long_name' "${informationFile}")
       # videoFoundFlag=true  # Used for error handling to confirm we found a video stream
     fi
-    if jq -e '.streams[] | select(.codec_type=="audio")' "${informationFile}" > /dev/null; then
+    if jq -e '.streams[] | select(.codec_type=="audio")' "${informationFile}" >/dev/null; then
       audioCodec=$(jq -r '.streams[] | select(.codec_type=="audio") | .codec_name' "${informationFile}")
       audioCodecLong=$(jq -r '.streams[] | select(.codec_type=="audio") | .codec_long_name' "${informationFile}")
       audioSampleRate=$(jq -r '.streams[] | select(.codec_type=="audio") | .sample_rate' "${informationFile}")
@@ -149,7 +148,7 @@ _mainScript_() {
       if [[ "${supportedAudioCodecs[*]}" =~ ${audioCodec} ]]; then
         videoAudioCommand="-c:a copy"
       elif [[ ${audioBitRate} -gt 163840 ]]; then # Downgrade to 160k
-          videoAudioCommand="-c:a ${aacEncoder} -b:a 160k" #163840 (160k in bytes)
+        videoAudioCommand="-c:a ${aacEncoder} -b:a 160k" #163840 (160k in bytes)
       else # Convert to aac but leave bitrate alone
         newBitRate=$((audioBitRate/1024))
         videoAudioCommand="-c:a ${aacEncoder} -b:a ${newBitRate}k"
@@ -264,7 +263,7 @@ _mainScript_() {
   _doConvert_() {
     verbose "\t beginning conversion..."
 
-    if ${verbose}; then v="-v" ; fi
+    if ${verbose}; then v="-v"; fi
 
     # Respect the 'Quiet' flag
     if "${quiet}"; then
@@ -281,20 +280,20 @@ _mainScript_() {
     _execute_ "caffeinate -ism ffmpeg -i \"${file}\" ${videoResize} ${videoCommand} ${videoAudioCommand} \"${output}\" ${ffquiet}"
 
     # Unset variables to get ready for the next file
-      unset jsonFilename
-      unset formatBit_Rate
-      unset numStreams
-      unset videoCodec
-      unset videoCodecLong
-      unset format
-      unset formatName
-      unset videoHeight
-      unset videoWidth
-      unset videoPreset
-      unset audioCodec
-      unset audioCodecLong
-      unset audioSampleRate
-      unset audioBitRate
+    unset jsonFilename
+    unset formatBit_Rate
+    unset numStreams
+    unset videoCodec
+    unset videoCodecLong
+    unset format
+    unset formatName
+    unset videoHeight
+    unset videoWidth
+    unset videoPreset
+    unset audioCodec
+    unset audioCodecLong
+    unset audioSampleRate
+    unset audioBitRate
   }
 
   _deleteOriginalFile_() {
@@ -334,9 +333,10 @@ _safeExit_() {
 
 _inArray_() {
   # v1.0.0
-  local value="$1"; shift
+  local value="$1"
+  shift
   for arrayItem in "$@"; do
-      [[ "${arrayItem}" == "${value}" ]] && return 0
+    [[ "${arrayItem}" == "${value}" ]] && return 0
   done
   return 1
 }
@@ -350,7 +350,7 @@ _execute_() {
     if $verbose; then
       eval "$1"
     else
-      eval "$1" &> /dev/null
+      eval "$1" &>/dev/null
     fi
     if [ $? -eq 0 ]; then
       success "${2:-$1}"
@@ -371,9 +371,9 @@ _seekConfirmation_() {
     while true; do
       read -r -p " (y/n) " yn
       case $yn in
-        [Yy]* ) return 0;;
-        [Nn]* ) return 1;;
-        * ) input "Please answer yes or no.";;
+        [Yy]*) return 0 ;;
+        [Nn]*) return 1 ;;
+        *) input "Please answer yes or no." ;;
       esac
     done
   fi
@@ -398,7 +398,7 @@ _realpath_() {
 
     # get the basename of the file (ignoring '.' & '..', because they're really part of the path)
     local file_basename="${path##*/}"
-    if [[ ( "$file_basename" = "." ) || ( "$file_basename" = ".." ) ]]; then
+    if [[ ("$file_basename" == ".") || ("$file_basename" == "..") ]]; then
       file_basename=""
     fi
 
@@ -409,13 +409,13 @@ _realpath_() {
     fi
 
     # attempt to change to the directory
-    if ! cd "$directory" &>/dev/null ; then
+    if ! cd "$directory" &>/dev/null; then
       success=false
     fi
 
     if $success; then
       # does the filename exist?
-      if [[ ( -n "$file_basename" ) && ( ! -e "$file_basename" ) ]]; then
+      if [[ (-n "$file_basename") && (! -e "$file_basename") ]]; then
         success=false
       fi
 
@@ -467,7 +467,7 @@ _uniqueFileName_() {
   if [ -e "${newfile}" ]; then
     local n=2
     while [[ -e "${directory}/${filename}${spacer}${n}${extension}" ]]; do
-      (( n++ ))
+      ((n++))
     done
     newfile="${directory}/${filename}${spacer}${n}${extension}"
   fi
@@ -477,12 +477,12 @@ _uniqueFileName_() {
 
 _setPATH_() {
   # setPATH() Add homebrew and ~/bin to $PATH so the script can find executables
-  PATHS=(/usr/local/bin ${HOME}/bin);
+  PATHS=(/usr/local/bin "${HOME}/bin")
   for newPath in "${PATHS[@]}"; do
-    if ! echo "$PATH" | grep -Eq "(^|:)${newPath}($|:)" ; then
+    if ! echo "$PATH" | grep -Eq "(^|:)${newPath}($|:)"; then
       PATH="${newPath}:${PATH}"
-   fi
- done
+    fi
+  done
 }
 _setPATH_
 
@@ -491,22 +491,35 @@ _setPATH_
 scriptName=$(basename "$0")
 
 # Set Flags
-quiet=false;              printLog=false;               verbose=false;
-force=false;              strict=false;                 dryrun=false;
-debug=false;              sourceOnly=false;             args=();
+quiet=false
+printLog=false
+verbose=false
+force=false
+strict=false
+dryrun=false
+debug=false
+sourceOnly=false
+args=()
 
-deleteOriginal=false;     dryrun=false;                testFiles=false;
-probe=false;
+deleteOriginal=false
+dryrun=false
+testFiles=false
+probe=false
 
 # Set Colors
-bold=$(tput bold);        reset=$(tput sgr0);           purple=$(tput setaf 171);
-red=$(tput setaf 1);      green=$(tput setaf 76);       tan=$(tput setaf 3);
-blue=$(tput setaf 38);    underline=$(tput sgr 0 1);
+bold=$(tput bold)
+reset=$(tput sgr0)
+purple=$(tput setaf 171)
+red=$(tput setaf 1)
+green=$(tput setaf 76)
+tan=$(tput setaf 3)
+blue=$(tput setaf 38)
+underline=$(tput sgr 0 1)
 
 # Set Temp Directory
-tmpDir="/tmp/${scriptName}.$RANDOM.$RANDOM.$RANDOM.$$"
+tmpDir="${TMPDIR-/tmp/}$(basename "$0").$RANDOM.$RANDOM.$$"
 (umask 077 && mkdir "${tmpDir}") || {
-  die "Could not create temporary directory! Exiting."
+  fatal "Could not create temporary directory! Exiting."
 }
 
 # Logging & Feedback
@@ -559,31 +572,69 @@ _alert_() {
   if [ "${1}" = "dryrun" ]; then local color="${blue}"; fi
   if [ "${1}" = "info" ] || [ "${1}" = "notice" ]; then local color=""; fi
   # Don't use colors on pipes or non-recognized terminals
-  if [[ "${TERM}" != "xterm"* ]] || [ -t 1 ]; then color=""; reset=""; fi
+  if [[ "${TERM}" != "xterm"* ]] || [ -t 1 ]; then
+    color=""
+    reset=""
+  fi
 
   # Print to console when script is not 'quiet'
-  if ${quiet}; then tput cuu1 ; return; else # tput cuu1 moves cursor up one line
-   echo -e "$(date +"%r") ${color}$(printf "[%7s]" "${1}") ${_message}${reset}";
+  if ${quiet}; then
+    tput cuu1
+    return
+  else # tput cuu1 moves cursor up one line
+    echo -e "$(date +"%r") ${color}$(printf "[%7s]" "${1}") ${_message}${reset}"
   fi
 
   # Print to Logfile
   if ${printLog} && [ "${1}" != "input" ]; then
-    color=""; reset="" # Don't use colors in logs
-    echo -e "$(date +"%m-%d-%Y %r") $(printf "[%7s]" "${1}") ${_message}" >> "${logFile}";
+    color=""
+    reset="" # Don't use colors in logs
+    echo -e "$(date +"%m-%d-%Y %r") $(printf "[%7s]" "${1}") ${_message}" >>"${logFile}"
   fi
 }
 
-function die ()       { local _message="${*} Exiting."; echo -e "$(_alert_ error)"; _safeExit_ "1";}
-function error ()     { local _message="${*}"; echo -e "$(_alert_ error)"; }
-function warning ()   { local _message="${*}"; echo -e "$(_alert_ warning)"; }
-function notice ()    { local _message="${*}"; echo -e "$(_alert_ notice)"; }
-function info ()      { local _message="${*}"; echo -e "$(_alert_ info)"; }
-function debug ()     { local _message="${*}"; echo -e "$(_alert_ debug)"; }
-function success ()   { local _message="${*}"; echo -e "$(_alert_ success)"; }
-function dryrun()     { local _message="${*}"; echo -e "$(_alert_ dryrun)"; }
-function input()      { local _message="${*}"; echo -n "$(_alert_ input)"; }
-function header()     { local _message="== ${*} ==  "; echo -e "$(_alert_ header)"; }
-function verbose()    { if ${verbose}; then debug "$@"; fi }
+function die() {
+  local _message="${*} Exiting."
+  echo -e "$(_alert_ error)"
+  _safeExit_ "1"
+}
+function error() {
+  local _message="${*}"
+  echo -e "$(_alert_ error)"
+}
+function warning() {
+  local _message="${*}"
+  echo -e "$(_alert_ warning)"
+}
+function notice() {
+  local _message="${*}"
+  echo -e "$(_alert_ notice)"
+}
+function info() {
+  local _message="${*}"
+  echo -e "$(_alert_ info)"
+}
+function debug() {
+  local _message="${*}"
+  echo -e "$(_alert_ debug)"
+}
+function success() {
+  local _message="${*}"
+  echo -e "$(_alert_ success)"
+}
+function dryrun() {
+  local _message="${*}"
+  echo -e "$(_alert_ dryrun)"
+}
+function input() {
+  local _message="${*}"
+  echo -n "$(_alert_ input)"
+}
+function header() {
+  local _message="== ${*} ==  "
+  echo -e "$(_alert_ header)"
+}
+function verbose() { if ${verbose}; then debug "$@"; fi; }
 
 # Iterate over options breaking -ab into -a -b when needed and --foo=bar into
 # --foo bar
@@ -594,7 +645,7 @@ while (($#)); do
     # If option is of type -ab
     -[!-]?*)
       # Loop over each character starting with the second
-      for ((i=1; i < ${#1}; i++)); do
+      for ((i = 1; i < ${#1}; i++)); do
         c=${1:i:1}
 
         # Add current char to options
@@ -602,7 +653,7 @@ while (($#)); do
 
         # If option takes a required argument, and it's not the last char make
         # the rest of the string its argument
-        if [[ $optstring = *"$c:"* && ${1:i+1} ]]; then
+        if [[ $optstring == *"$c:"* && ${1:i+1} ]]; then
           options+=("${1:i+1}")
           break
         fi
@@ -627,25 +678,43 @@ unset options
 [[ $# -eq 0 ]] && set -- "--help"
 
 # Read the options and set stuff
-while [[ $1 = -?* ]]; do
+while [[ $1 == -?* ]]; do
   case $1 in
 
-    -o|--output) shift; outputFormat="${1,,}" ;;
-    -n|--dryrun) dryrun=true ;;
-    -h|--help) _usage_ >&2; _safeExit_ ;;
-    -v|--verbose) verbose=true ;;
-    -l|--log) printLog=true ;;
-    -q|--quiet) quiet=true ;;
-    -s|--strict) strict=true;;
-    -d|--debug) debug=true;;
-    --probe) probe=true; dryrun=true ;;
-    --size) shift; outputVideoSize="$1" ;;
+    -o | --output)
+      shift
+      outputFormat="${1,,}"
+      ;;
+    -n | --dryrun) dryrun=true ;;
+    -h | --help)
+      _usage_ >&2
+      _safeExit_
+      ;;
+    -v | --verbose) verbose=true ;;
+    -l | --log) printLog=true ;;
+    -q | --quiet) quiet=true ;;
+    -s | --strict) strict=true ;;
+    -d | --debug) debug=true ;;
+    --probe)
+      probe=true
+      dryrun=true
+      ;;
+    --size)
+      shift
+      outputVideoSize="$1"
+      ;;
     --testFiles) testFiles=true ;;
     --delete) deleteOriginal=true ;;
-    --version) echo "$(basename $0) ${version}"; _safeExit_ ;;
-    --source-only) sourceOnly=true;;
+    --version)
+      echo "$(basename $0) ${version}"
+      _safeExit_
+      ;;
+    --source-only) sourceOnly=true ;;
     --force) force=true ;;
-    --endopts) shift; break ;;
+    --endopts)
+      shift
+      break
+      ;;
     *) die "invalid option: '$1'." ;;
   esac
   shift
@@ -664,10 +733,10 @@ IFS=$' \n\t'
 #set -o errexit
 
 # Run in debug mode, if set
-if ${debug}; then set -x ; fi
+if ${debug}; then set -x; fi
 
 # Exit on empty variable
-if ${strict}; then set -o nounset ; fi
+if ${strict}; then set -o nounset; fi
 
 # Bash will remember & return the highest exitcode in a chain of pipes.
 # This way you can catch the error in case mysqldump fails in `mysqldump |gzip`, for example.
diff --git a/bin/removeSymlink b/bin/removeSymlink
--- a/bin/removeSymlink
+++ b/bin/removeSymlink
@@ -7,7 +7,7 @@ _mainScript_() {
   _errorHandling_() {
     # This script requires the Linux gdate (as opposed to native 'date' in OSX)
     # Here we see if it's installed. If not, we install it with homebrew.
-    if ! command -v dirname &> /dev/null; then
+    if ! command -v dirname &>/dev/null; then
       warning "Need 'dirname' to continue. Installing via homebrew."
       brew install coreutils
       success "'coreutils' package installed. Exiting."
@@ -16,9 +16,12 @@ _mainScript_() {
   }
   _errorHandling_
 
-  links=( "${args[@]}" )
+  links=("${args[@]}")
 
-  [[ ${#links[@]} == 0 ]] && { notice "No link specified"; _safeExit_; }
+  [[ ${#links[@]} == 0 ]] && {
+    notice "No link specified"
+    _safeExit_
+  }
 
   # Work through the links
   for link in "${links[@]}"; do
@@ -29,8 +32,8 @@ _mainScript_() {
     dir=$(dirname "${link}")
     reltarget=$(readlink "${link}")
     case "${reltarget}" in
-        /*) abstarget="${reltarget}";;
-        *)  abstarget="${dir}"/"${reltarget}";;
+      /*) abstarget="${reltarget}" ;;
+      *) abstarget="${dir}"/"${reltarget}" ;;
     esac
     if [ -e "${abstarget}" ]; then
       _execute_ "rm -f \"${link}\""
@@ -56,23 +59,33 @@ _mainScript_() {
 scriptName=$(basename "$0")
 
 # Set Flags
-quiet=false;              printLog=false;             logErrors=true;     verbose=false;
-force=false;              strict=false;               dryrun=false;
-debug=false;              sourceOnly=false;           args=();
+quiet=false
+printLog=false
+logErrors=true
+verbose=false
+force=false
+strict=false
+dryrun=false
+debug=false
+sourceOnly=false
+args=()
 
-replaceSymlink=false;
+replaceSymlink=false
 
 _sourceHelperFiles_() {
   local filesToSource
   local sourceFile
 
   filesToSource=(
-    ${HOME}/dotfiles/scripting/helpers/baseHelpers.bash
+    '${HOME}/dotfiles/scripting/helpers/baseHelpers.bash'
   )
 
   for sourceFile in "${filesToSource[@]}"; do
     [ ! -f "$sourceFile" ] \
-      &&  { echo "error: Can not find sourcefile '$sourceFile'. Exiting."; exit 1; }
+      && {
+        echo "error: Can not find sourcefile '$sourceFile'. Exiting."
+        exit 1
+      }
 
     source "$sourceFile"
   done
@@ -115,7 +128,7 @@ while (($#)); do
     # If option is of type -ab
     -[!-]?*)
       # Loop over each character starting with the second
-      for ((i=1; i < ${#1}; i++)); do
+      for ((i = 1; i < ${#1}; i++)); do
         c=${1:i:1}
 
         # Add current char to options
@@ -123,7 +136,7 @@ while (($#)); do
 
         # If option takes a required argument, and it's not the last char make
         # the rest of the string its argument
-        if [[ $optstring = *"$c:"* && ${1:i+1} ]]; then
+        if [[ $optstring == *"$c:"* && ${1:i+1} ]]; then
           options+=("${1:i+1}")
           break
         fi
@@ -148,20 +161,29 @@ unset options
 [[ $# -eq 0 ]] && set -- "--help"
 
 # Read the options and set stuff
-while [[ $1 = -?* ]]; do
+while [[ $1 == -?* ]]; do
   case $1 in
-    -r|--replace) replaceSymlink=true ;;
-    -L|--noErrorLog) logErrors=false ;;
-    -h|--help) usage >&2; _safeExit_ ;;
-    --version) echo "$(basename $0) ${version}"; _safeExit_ ;;
-    -n|--dryrun) dryrun=true ;;
-    -v|--verbose) verbose=true ;;
-    -q|--quiet) quiet=true ;;
-    -s|--strict) strict=true;;
-    -d|--debug) debug=true;;
-    --source-only) sourceOnly=true;;
+    -r | --replace) replaceSymlink=true ;;
+    -L | --noErrorLog) logErrors=false ;;
+    -h | --help)
+      usage >&2
+      _safeExit_
+      ;;
+    --version)
+      echo "$(basename $0) ${version}"
+      _safeExit_
+      ;;
+    -n | --dryrun) dryrun=true ;;
+    -v | --verbose) verbose=true ;;
+    -q | --quiet) quiet=true ;;
+    -s | --strict) strict=true ;;
+    -d | --debug) debug=true ;;
+    --source-only) sourceOnly=true ;;
     --force) force=true ;;
-    --endopts) shift; break ;;
+    --endopts)
+      shift
+      break
+      ;;
     *) die "invalid option: '$1'." ;;
   esac
   shift
@@ -182,10 +204,10 @@ IFS=$' \n\t'
 #set -o errexit
 
 # Run in debug mode, if set
-if ${debug}; then set -x ; fi
+if ${debug}; then set -x; fi
 
 # Exit on empty variable
-if ${strict}; then set -o nounset ; fi
+if ${strict}; then set -o nounset; fi
 
 # Run your script unless in 'source-only' mode
 if ! ${sourceOnly}; then _mainScript_; fi
diff --git a/bin/unlockFile b/bin/unlockFile
--- a/bin/unlockFile
+++ b/bin/unlockFile
@@ -8,12 +8,15 @@ function _mainScript_() {
 
   # Exit if the specified arg is not a file
   [ ! -f "$userFile" ] \
-    && { warning "No such file '${userFile}'"; _safeExit_ 1; }
+    && {
+      warning "No such file '${userFile}'"
+      _safeExit_ 1
+    }
 
   s=$(fuser -f "$userFile")
-  PROCS=( $s )
+  PROCS=($s)
 
-  if [ "${#PROCS[@]}" == 0 ] ; then
+  if [ "${#PROCS[@]}" == 0 ]; then
     warning "File '$userFile' is not open."
   else
     for element in "${PROCS[@]}"; do
@@ -24,10 +27,10 @@ function _mainScript_() {
     input "Type the PID number to kill a given process, 'a' to kill all, or 'q' to quit: "
     read -r REPLY
 
-    if [ "$REPLY" == "a" ] || [ "$REPLY" == "A" ] ; then
+    if [ "$REPLY" == "a" ] || [ "$REPLY" == "A" ]; then
       for element in "${PROCS[@]}"; do
-       _execute_ "kill $element" \
-        || die "Error killing processes.";
+        _execute_ "kill $element" \
+          || die "Error killing processes."
       done
     elif [ "$REPLY" == "q" ] || [ "$REPLY" == "Q" ]; then
       notice "User canceled. Exiting."
@@ -49,7 +52,10 @@ _sourceHelperFiles_() {
 
   for sourceFile in "${filesToSource[@]}"; do
     [ ! -f "$sourceFile" ] \
-      &&  { echo "error: Can not find sourcefile '$sourceFile'. Exiting."; exit 1; }
+      && {
+        echo "error: Can not find sourcefile '$sourceFile'. Exiting."
+        exit 1
+      }
 
     source "$sourceFile"
   done
@@ -61,13 +67,20 @@ _sourceHelperFiles_
 scriptName=$(basename "$0")
 
 # Set Flags
-quiet=false;              printLog=false;             logErrors=true;     verbose=false;
-force=false;              strict=false;               dryrun=false;
-debug=false;              sourceOnly=false;           args=();
+quiet=false
+printLog=false
+logErrors=true
+verbose=false
+force=false
+strict=false
+dryrun=false
+debug=false
+sourceOnly=false
+args=()
 
 # Options and Usage
 # -----------------------------------
-_usage_ () {
+_usage_() {
   echo -n "${scriptName} [OPTION]... [FILE]...
 
 This script takes a user specified filename and finds processes that are keeping
@@ -104,7 +117,7 @@ while (($#)); do
     # If option is of type -ab
     -[!-]?*)
       # Loop over each character starting with the second
-      for ((i=1; i < ${#1}; i++)); do
+      for ((i = 1; i < ${#1}; i++)); do
         c=${1:i:1}
 
         # Add current char to options
@@ -112,7 +125,7 @@ while (($#)); do
 
         # If option takes a required argument, and it's not the last char make
         # the rest of the string its argument
-        if [[ $optstring = *"$c:"* && ${1:i+1} ]]; then
+        if [[ $optstring == *"$c:"* && ${1:i+1} ]]; then
           options+=("${1:i+1}")
           break
         fi
@@ -137,20 +150,29 @@ unset options
 [[ $# -eq 0 ]] && set -- "--help"
 
 # Read the options and set stuff
-while [[ $1 = -?* ]]; do
+while [[ $1 == -?* ]]; do
   case $1 in
-    -h|--help) _usage_ >&2; _safeExit_ ;;
-    -L|--noErrorLog) logErrors=false ;;
-    -n|--dryrun) dryrun=true ;;
-    -v|--verbose) verbose=true ;;
-    -l|--log) printLog=true ;;
-    -q|--quiet) quiet=true ;;
-    -s|--strict) strict=true;;
-    -d|--debug) debug=true;;
-    --version) echo "$(basename $0) ${version}"; _safeExit_ ;;
-    --source-only) sourceOnly=true;;
+    -h | --help)
+      _usage_ >&2
+      _safeExit_
+      ;;
+    -L | --noErrorLog) logErrors=false ;;
+    -n | --dryrun) dryrun=true ;;
+    -v | --verbose) verbose=true ;;
+    -l | --log) printLog=true ;;
+    -q | --quiet) quiet=true ;;
+    -s | --strict) strict=true ;;
+    -d | --debug) debug=true ;;
+    --version)
+      echo "$(basename $0) ${version}"
+      _safeExit_
+      ;;
+    --source-only) sourceOnly=true ;;
     --force) force=true ;;
-    --endopts) shift; break ;;
+    --endopts)
+      shift
+      break
+      ;;
     *) die "invalid option: '$1'." ;;
   esac
   shift
@@ -159,7 +181,6 @@ done
 # Store the remaining part as an argument.
 #args+=("$@")
 userFile="$1"
-
 
 # Trap bad exits with your cleanup function
 trap '_trapCleanup_ $LINENO $BASH_LINENO "$BASH_COMMAND" "${FUNCNAME[*]}" "$0" "${BASH_SOURCE[0]}"' \
@@ -176,10 +197,10 @@ IFS=$' \n\t'
 set -o pipefail
 
 # Run in debug mode, if set
-if ${debug}; then set -x ; fi
+if ${debug}; then set -x; fi
 
 # Exit on empty variable
-if ${strict}; then set -o nounset ; fi
+if ${strict}; then set -o nounset; fi
 
 # Run your script unless in 'source-only' mode
 if ! ${sourceOnly}; then _mainScript_; fi
diff --git a/bin/upgradeCasks b/bin/upgradeCasks
--- a/bin/upgradeCasks
+++ b/bin/upgradeCasks
@@ -13,17 +13,19 @@ _mainScript_() {
 
     # Sometimes license files can get old and cause 'brew cask' to throw errors.  This can help
     # identify the culprits
-    for cask in $(grep -ilr --include \*.rb license $(brew --prefix)/Caskroom/*/.metadata | awk -F '/' '{print $5}' | sort -u); do
+    while read -r cask; do
       verbose "If 'brew cask list' throws license errors attempt to reinstall '$cask'"
       # find $(brew --prefix)/Caskroom/${cask}/.metadata -name "*.rb" -exec sed -i'' -e 's/license/#license/' {} \;
       #_execute_ "brew cask reinstall $cask"
-    done
+    done < <(grep -ilr --include \*.rb license $(brew --prefix)/Caskroom/*/.metadata | awk -F '/' '{print $5}' | sort -u)
 
     # Reinstall outdated casks
-    v=$verbose; verbose=true;
+    v=$verbose
+    verbose=true
     if [[ $(brew cask outdated) != "" ]]; then
-      casks=( $(brew cask list) )
+      mapfile -t casks < <(brew cask list)
       for cask in "${casks[@]}"; do
+        echo "$cask"
         version=$(brew cask info $cask | sed -n "s/$cask:\ \(.*\)/\1/p")
         installed=$(find "/usr/local/Caskroom/$cask" -type d -maxdepth 1 -maxdepth 1 -name "$version")
         if [[ -z $installed ]]; then
@@ -39,19 +41,22 @@ _mainScript_() {
   }
   _upgradeCasks_
 
-}  # end _mainScript_
+} # end _mainScript_
 
 _sourceHelperFiles_() {
   local filesToSource
   local sourceFile
 
   filesToSource=(
-    ${HOME}/dotfiles/scripting/helpers/baseHelpers.bash
+    "${HOME}/dotfiles/scripting/helpers/baseHelpers.bash"
   )
 
   for sourceFile in "${filesToSource[@]}"; do
     [ ! -f "$sourceFile" ] \
-      &&  { echo "error: Can not find sourcefile '$sourceFile'. Exiting."; exit 1; }
+      && {
+        echo "error: Can not find sourcefile '$sourceFile'. Exiting."
+        exit 1
+      }
 
     source "$sourceFile"
   done
@@ -63,9 +68,16 @@ _sourceHelperFiles_
 scriptName=$(basename "$0")
 
 # Set Flags
-quiet=false;              printLog=false;             logErrors=true;     verbose=false;
-force=false;              strict=false;               dryrun=false;
-debug=false;              sourceOnly=false;           args=();
+quiet=false
+printLog=false
+logErrors=true
+verbose=false
+force=false
+strict=false
+dryrun=false
+debug=false
+sourceOnly=false
+args=()
 
 # Options and Usage
 # -----------------------------------
@@ -99,7 +111,7 @@ while (($#)); do
     # If option is of type -ab
     -[!-]?*)
       # Loop over each character starting with the second
-      for ((i=1; i < ${#1}; i++)); do
+      for ((i = 1; i < ${#1}; i++)); do
         c=${1:i:1}
 
         # Add current char to options
@@ -107,7 +119,7 @@ while (($#)); do
 
         # If option takes a required argument, and it's not the last char make
         # the rest of the string its argument
-        if [[ $optstring = *"$c:"* && ${1:i+1} ]]; then
+        if [[ $optstring == *"$c:"* && ${1:i+1} ]]; then
           options+=("${1:i+1}")
           break
         fi
@@ -132,20 +144,29 @@ unset options
 # [[ $# -eq 0 ]] && set -- "--help"
 
 # Read the options and set stuff
-while [[ $1 = -?* ]]; do
+while [[ $1 == -?* ]]; do
   case $1 in
-    -h|--help) _usage_ >&2; _safeExit_ ;;
-    -L|--noErrorLog) logErrors=false ;;
-    -n|--dryrun) dryrun=true ;;
-    -v|--verbose) verbose=true ;;
-    -l|--log) printLog=true ;;
-    -q|--quiet) quiet=true ;;
-    -s|--strict) strict=true;;
-    -d|--debug) debug=true;;
-    --version) echo "$(basename $0) ${version}"; _safeExit_ ;;
-    --source-only) sourceOnly=true;;
+    -h | --help)
+      _usage_ >&2
+      _safeExit_
+      ;;
+    -L | --noErrorLog) logErrors=false ;;
+    -n | --dryrun) dryrun=true ;;
+    -v | --verbose) verbose=true ;;
+    -l | --log) printLog=true ;;
+    -q | --quiet) quiet=true ;;
+    -s | --strict) strict=true ;;
+    -d | --debug) debug=true ;;
+    --version)
+      echo "$(basename $0) ${version}"
+      _safeExit_
+      ;;
+    --source-only) sourceOnly=true ;;
     --force) force=true ;;
-    --endopts) shift; break ;;
+    --endopts)
+      shift
+      break
+      ;;
     *) die "invalid option: '$1'." ;;
   esac
   shift
@@ -169,10 +190,10 @@ IFS=$' \n\t'
 set -o pipefail
 
 # Run in debug mode, if set
-if ${debug}; then set -x ; fi
+if ${debug}; then set -x; fi
 
 # Exit on empty variable
-if ${strict}; then set -o nounset ; fi
+if ${strict}; then set -o nounset; fi
 
 # Run your script unless in 'source-only' mode
 if ! ${sourceOnly}; then _mainScript_; fi
