Shared scripting libraries
  - configure scripts to use scripting helpers
  - rework BATS tests
  - add _executeStrict_ function

diff --git a/bin/cleanFilenames b/bin/cleanFilenames
--- a/bin/cleanFilenames
+++ b/bin/cleanFilenames
@@ -23,27 +23,53 @@ _mainScript_() {
 
     # Ensure file exists
     if [ ! -e "${userFile}" ]; then
-      die "No such file or directory: '${userFile}'"
+      error "No such file or directory: '${userFile}'" "$LINENO"
+      return 1
     fi
     # Ignore directories
     if [ -d "${userFile}" ]; then
-      die "${userFile}: is a directory."
+      error "${userFile}: is a directory." "$LINENO"
+      return 1
     fi
     # Ignore dotfiles
     regex="^\..*"
     if [[ "${userFile}" =~ ${regex} ]]; then
-      die "${userFile}: is a dotfile."
+      error "${userFile}: is a dotfile." "$LINENO"
+      return 1
     fi
     # Don't act on files without extensions
     if [[ "${userFile##*.}" == "" || "${userFile##*.}" == "${userFile}" ]]; then
-      die "${userFile}: we need a file extension"
+      error "${userFile}: we need a file extension" "$LINENO"
+      return 1
     fi
     # Ignore certain file types
     regex="dmg"
     if [[ "${userFile##*.}" =~ ${regex} ]]; then
-      die "'.${userFile##*.}' is not a supported extension"
+      error "'.${userFile##*.}' is not a supported extension" "$LINENO"
     fi
     return 0
+  }
+
+  _parseFilename_() {
+    # Here we parse the user's file into it's directory, basename, and extension.
+    local fileToParse="${1:?No file provided to _parseFilename_}"
+
+    # Grab the directory
+    if ! ${testOutput}; then originalFileWithPath="$(_realpath_ "${fileToParse}")"; fi
+    verbose "originalFileWithPath: $originalFileWithPath"
+    filePath=$(dirname "$originalFileWithPath") && verbose "filePath: $filePath"
+
+    # use the basename of the userFile going forward since the path is now in $filePath
+    userFile=$(basename "${fileToParse}") && verbose "userfile: $userFile"
+
+    # Grab the filename without the extension
+    baseFilename="${userFile%.*}" && verbose "baseFilename: $baseFilename"
+
+    # Grab the extension
+    extension="$(_ext_ "${userFile}")" && verbose "extension: $extension"
+
+    # Keep track of the original file for future comparison
+    originalFile="${baseFilename}${extension}" && verbose "originalFile: $originalFile"
   }
 
   _clean_() {
@@ -241,7 +267,7 @@ _mainScript_() {
     baseFilename="$(_clean_ "$baseFilename")"
 
     # Add the extension back to the filename
-    newFilename="${baseFilename}.${extension}"
+    newFilename="${baseFilename}${extension}"
   }
 
   _renameFiles_() {
@@ -250,21 +276,18 @@ _mainScript_() {
 
     # If the filename has not changed then do nothing
     if [[ "${newFilename}" == "${originalFile}" ]]; then
-      notice "${userFile}: No change"
+      if ${nonInteractive}; then
+        echo "${originalFileWithPath}"
+      else
+        notice "${userFile}: No change"
+      fi
       return
     fi
 
-    if [ ! -e "${newFilename}" ]; then
-      _execute_ "mv \"${originalFileWithPath}\" \"${filePath}/${newFilename}\"" "${userFile} --> ${newFilename}"
-    else
-      local i=2
-      newFilename="${baseFilename} ${i}.${extension}"
-      while [ -e "${newFilename}" ]; do
-        ((i=i+1))
-        newFilename="${baseFilename} ${i}.${extension}"
-      done
-      _execute_ "mv \"${originalFileWithPath}\" \"${filePath}/${newFilename}\"" "${userFile} --> ${newFilename}"
-    fi
+    newFile="$(_uniqueFileName_ "${filePath}/${newFilename}")" \
+      && verbose "\t newFile: $newFile"
+
+    _execute_ "mv \"${originalFileWithPath}\" \"${newFile}\"" "${userFile} --> ${newFile##*/}"
   }
 
   # Run the script functions
@@ -277,33 +300,11 @@ _mainScript_() {
       _findDate_
       _rebuildFileName_
       _renameFiles_
-      if ${nonInteractive}; then echo "${newFilename}" ; fi
+      if ${nonInteractive}; then echo "${newFile}" ; fi
     fi
   done
 
 } # end _mainScript_
-
-_parseFilename_() {
-  # Here we parse the user's file into it's directory, basename, and extension.
-  local fileToParse="${1:?No file provided to _parseFilename_}"
-
-  # Grab the directory
-  if ! ${testOutput}; then originalFileWithPath="$(_realpath_ "${fileToParse}")"; fi
-  verbose "originalFileWithPath: $originalFileWithPath"
-  filePath=$(dirname "$originalFileWithPath") && verbose "filePath: $filePath"
-
-  # use the basename of the userFile going forward since the path is now in $filePath
-  userFile=$(basename "${fileToParse}") && verbose "userfile: $userFile"
-
-  # Grab the Filename without the extension
-  baseFilename="${userFile%.*}" && verbose "baseFilename: $baseFilename"
-
-  # Grab the extension
-  extension="${userFile##*.}"
-
-  # Keep track of the original file for future comparison
-  originalFile="${baseFilename}.${extension}"
-}
 
 filesToSource=(
   ${HOME}/dotfiles/scripting/helpers/baseHelpers.bash
@@ -312,7 +313,7 @@ filesToSource=(
 
 for sourceFile in "${filesToSource[@]}"; do
   [ ! -f "$sourceFile" ] \
-    &&  { echo "error: Can not find sourcefile '$sourceFile'. Exiting."; return 1; }
+    &&  { echo "error: Can not find sourcefile '$sourceFile'. Exiting."; exit 1; }
 
   source "$sourceFile"
 done
@@ -322,9 +323,9 @@ done
 scriptName=$(basename "$0")
 
 # Set Flags
-quiet=false;        printLog=true;             verbose=false;
-force=false;        strict=false;               dryrun=false;
-debug=false;        sourceOnly=false;           args=();
+quiet=false;        printLog=false;            logErrors=true;    verbose=false;
+force=false;        strict=false;              dryrun=false;
+debug=false;        sourceOnly=false;          args=();
 
 cleanOnly=false;    nonInteractive=false;       lowerCase=false;
 ignoreFile=false;   removeDates=false;          testOutput=false;
@@ -360,7 +361,7 @@ _usage_() {
       2) The date the file was created.
       3) Today's date.
 
-   ${bold}Options:${reset}
+  ${bold}Options:${reset}
 
     -C, --clean       Cleans a filename of special characters and normalizes dates
                       already in the filename but does NOT prepend a date if none
@@ -372,6 +373,7 @@ _usage_() {
                       output in this mode is an exit code and the cleaned name of the file
                       passed to the script
 
+    -e, --noErrorLog  Print log level error and fatal to a log (default 'true')
     -T, --test        Takes a string of input and shows the result that the script would produce
 
     -n, --dryrun      Non-destructive run. Will report on changes that would have
@@ -385,7 +387,7 @@ _usage_() {
         --source-only Bypasses main script functionality to allow unit tests of functions
         --version     Output version information and exit
 
-   ${bold}Examples:${reset}
+  ${bold}Examples:${reset}
 
     Original Filename: 'filename (with special chars & and date) 08312016.txt'
     Cleaned Filename : '2016-08-31 filename with special chars-and date.txt'
@@ -442,6 +444,7 @@ while [[ $1 = -?* ]]; do
     -C|--clean) cleanOnly=true ;;
     -R| --removeDate) removeDates=true ;;
     -L| --lower) lowerCase=true ;;
+    -e|--noErrorLog) logErrors=false ;;
     -n|--dryrun) dryrun=true ;;
     --nonInteractive) nonInteractive=true; quiet=true; ;;
     -h|--help) _usage_ >&2 ; _safeExit_ ;;
@@ -463,23 +466,22 @@ done
 args+=("$@")
 
 # Trap bad exits with your cleanup function
-trap '_trapCleanup_ $LINENO' EXIT INT TERM
+trap '_trapCleanup_ $LINENO $BASH_LINENO "$BASH_COMMAND" "${FUNCNAME[*]}" "$0" "${BASH_SOURCE[0]}" "${userFile}' \
+  EXIT INT TERM SIGINT SIGQUIT ERR
 
 # Set IFS to preferred implementation
 IFS=$' \n\t'
 
 # Exit on error. Append '||true' when you run the script if you expect an error.
 # if using the '_execute_' function this must be disabled for warnings to be shown if tasks fail
-#set -o errexit
+# set -o errexit
+# set -o errtrace
 
 # Run in debug mode, if set
 if ${debug}; then set -x ; fi
 
 # Exit on empty variable
 if ${strict}; then set -o nounset ; fi
-
-# Exit the script if a command fails
-set -e
 
 # Run your script unless in source only mode
 if ! ${sourceOnly}; then _mainScript_ ; fi
diff --git a/bin/trash b/bin/trash
--- a/bin/trash
+++ b/bin/trash
@@ -101,11 +101,15 @@ _mainScript_() {
 
   _trashAFile_() {
     local baseFile
+    local new
+    local newBase
+    local trash
 
     # Iterate over all files passed by user
     for userFile in "${args[@]}"; do
       if [ ! -e "${userFile}" ]; then
-        die "${userFile}: No such file or directory"
+        warning "${userFile}: No such file or directory"
+        continue
       fi
 
       # determine whether we have an absolute path name to the file or not
@@ -125,13 +129,13 @@ _mainScript_() {
       _execute_ "/usr/bin/osascript -e 'tell application \"Finder\" to delete POSIX file \"${userFile}\"' &>/dev/null" "'${baseFile}' moved to trash"
     else
       verbose "Telling system to trash '${baseFile}'..."
-      local trash="/Users/${user}/.Trash/"
+      trash="/Users/${user}/.Trash/"
       # create the trash folder if necessary
       if [ ! -d "${trash}" ]; then
         _execute_ "mkdir \"${trash}\""
       fi
-      local newBase="$(basename "${userFile}")"
-      local new="$(_uniqueFileName_ "${trash}${newBase}")"
+      newBase="$(basename "${userFile}")"
+      new="$(_uniqueFileName_ "${trash}${newBase}")"
       _execute_ "mv \"${userFile}\" \"${new}\"" "'${baseFile}' moved to trash"
     fi
     done
@@ -143,173 +147,29 @@ _mainScript_() {
   _trashAFile_
 }  # end _mainScript_
 
-_trapCleanup_() {
-  echo ""
-  die "Exit trapped. In function: '${FUNCNAME[*]:1}'"
-}
+filesToSource=(
+  ${HOME}/dotfiles/scripting/helpers/baseHelpers.bash
+  ${HOME}/dotfiles/scripting/helpers/files.bash
+)
 
-_safeExit_() {
-  trap - INT TERM EXIT
-  exit ${1:-0}
-}
+for sourceFile in "${filesToSource[@]}"; do
+  [ ! -f "$sourceFile" ] \
+    &&  { echo "error: Can not find sourcefile '$sourceFile'. Exiting."; exit 1; }
 
-_realpath_() {
-  # v1.0.0
-  local success=true
-  local path="$1"
-
-  # make sure the string isn't empty as that implies something in further logic
-  if [ -z "$path" ]; then
-    success=false
-  else
-    # start with the file name (sans the trailing slash)
-    path="${path%/}"
-
-    # if we stripped off the trailing slash and were left with nothing, that means we're in the root directory
-    if [ -z "$path" ]; then
-      path="/"
-    fi
-
-    # get the basename of the file (ignoring '.' & '..', because they're really part of the path)
-    local file_basename="${path##*/}"
-    if [[ ( "$file_basename" = "." ) || ( "$file_basename" = ".." ) ]]; then
-      file_basename=""
-    fi
-
-    # extracts the directory component of the full path, if it's empty then assume '.' (the current working directory)
-    local directory="${path%$file_basename}"
-    if [ -z "$directory" ]; then
-      directory='.'
-    fi
-
-    # attempt to change to the directory
-    if ! cd "$directory" &>/dev/null ; then
-      success=false
-    fi
-
-    if $success; then
-      # does the filename exist?
-      if [[ ( -n "$file_basename" ) && ( ! -e "$file_basename" ) ]]; then
-        success=false
-      fi
-
-      # get the absolute path of the current directory & change back to previous directory
-      local abs_path
-      abs_path="$(pwd -P)"
-      cd "-" &>/dev/null || return
-
-      # Append base filename to absolute path
-      if [ "${abs_path}" = "/" ]; then
-        abs_path="${abs_path}${file_basename}"
-      else
-        abs_path="${abs_path}/${file_basename}"
-      fi
-
-      # output the absolute path
-      echo "$abs_path"
-    fi
-  fi
-
-  $success
-}
-
-_execute_() {
-  # v1.0.0
-  if ${dryrun}; then
-    dryrun "${2:-$1}"
-  else
-    #set +e # don't exit script if execute fails
-    if $verbose; then
-      eval "$1"
-    else
-      eval "$1" &> /dev/null
-    fi
-    if [ $? -eq 0 ]; then
-      success "${2:-$1}"
-    else
-      warning "${2:-$1}"
-    fi
-    # set -e
-  fi
-}
-
-_uniqueFileName_() {
-  # v1.0.0
-
-  local n origFull origName origExt newfile spacer
-
-  origFull="${1:?Can not proceed without file _uniqueFileName_}"
-  spacer="${2:- }"
-  origName="${origFull%.*}"
-  origExt="${origFull##*.}"
-  newfile="${origName}.${origExt}"
-
-  if [ -e "${newfile}" ]; then
-    n=2
-    while [[ -e "${origName}${spacer}${n}.${origExt}" ]]; do
-      (( n++ ))
-    done
-    newfile="${origName}${spacer}${n}.${origExt}"
-  fi
-
-  echo "${newfile}"
-}
+  source "$sourceFile"
+done
 
 # Set Base Variables
 # ----------------------
 scriptName=$(basename "$0")
 
 # Set Flags
-quiet=false;      printLog=false;       verbose=false;
+quiet=false;      printLog=false;       logErrors=true;       verbose=false;
 strict=false;     dryrun=false;         sourceOnly=false;
 debug=false;      args=();
 
 list=false;       emptyTrash=false;    bypassFinder="false"
 systemRM=false
-
-# Set Colors
-bold=$(tput bold);        reset=$(tput sgr0);         purple=$(tput setaf 171);
-red=$(tput setaf 1);      green=$(tput setaf 76);      tan=$(tput setaf 3);
-blue=$(tput setaf 38);    underline=$(tput sgr 0 1);
-
-# Logging & Feedback
-logFile="${HOME}/Library/Logs/${scriptName%.sh}.log"
-
-_alert_() {
-  if [ "${1}" = "error" ]; then local color="${bold}${red}"; fi
-  if [ "${1}" = "warning" ]; then local color="${red}"; fi
-  if [ "${1}" = "success" ]; then local color="${green}"; fi
-  if [ "${1}" = "debug" ]; then local color="${purple}"; fi
-  if [ "${1}" = "header" ]; then local color="${bold}${tan}"; fi
-  if [ "${1}" = "input" ]; then local color="${bold}"; fi
-  if [ "${1}" = "dryrun" ]; then local color="${blue}"; fi
-  if [ "${1}" = "info" ] || [ "${1}" = "notice" ]; then local color=""; fi
-  # Don't use colors on pipes or non-recognized terminals
-  if [[ "${TERM}" != "xterm"* ]] || [ -t 1 ]; then color=""; reset=""; fi
-
-  # Print to console when script is not 'quiet'
-  if ${quiet}; then tput cuu1 ; return; else # tput cuu1 moves cursor up one line
-   echo -e "$(date +"%r") ${color}$(printf "[%7s]" "${1}") ${_message}${reset}";
-  fi
-
-  # Print to Logfile
-  if ${printLog} && [ "${1}" != "input" ]; then
-    color=""; reset="" # Don't use colors in logs
-    echo -e "$(date +"%m-%d-%Y %r") $(printf "[%7s]" "${1}") ${_message}" >> "${logFile}";
-  fi
-}
-
-function die ()       { local _message="${*} Exiting."; echo -e "$(_alert_ error)"; _safeExit_ "1";}
-function error ()     { local _message="${*}"; echo -e "$(_alert_ error)"; }
-function warning ()   { local _message="${*}"; echo -e "$(_alert_ warning)"; }
-function notice ()    { local _message="${*}"; echo -e "$(_alert_ notice)"; }
-function info ()      { local _message="${*}"; echo -e "$(_alert_ info)"; }
-function debug ()     { local _message="${*}"; echo -e "$(_alert_ debug)"; }
-function success ()   { local _message="${*}"; echo -e "$(_alert_ success)"; }
-function dryrun()     { local _message="${*}"; echo -e "$(_alert_ dryrun)"; }
-function input()      { local _message="${*}"; echo -n "$(_alert_ input)"; }
-function header()     { local _message="== ${*} ==  "; echo -e "$(_alert_ header)"; }
-function verbose()    { if ${verbose}; then debug "$@"; fi }
 
 
 # Options and Usage
@@ -330,6 +190,7 @@ _usage_() {
 
  ${bold}Options:${reset}
   -l , --list         List trash contents
+  -L, --noErrorLog    Print log level error and fatal to a log (default 'true')
   -e, --empty         Empty trash contents
   -n, --dryrun        Non-destructive run.
   -s, --system        Forces native Unix 'rm' command
@@ -391,8 +252,7 @@ while [[ $1 = -?* ]]; do
     --version) echo "$(basename $0) ${version}"; _safeExit_ ;;
     --bypassFinder) bypassFinder=true ;;
     -s|--system) systemRM=true ;;
-
-
+    -L|--noErrorLog) logErrors=false ;;
     -l|--list) list=true ;;
     -e|--empty) emptyTrash=true ;;
     -n|--dryrun) dryrun=true ;;
@@ -412,22 +272,21 @@ done
 args+=("$@")
 
 # Trap bad exits with your cleanup function
-trap _trapCleanup_ EXIT INT TERM
+trap '_trapCleanup_ $LINENO $BASH_LINENO "$BASH_COMMAND" "${FUNCNAME[*]}" "$0" "${BASH_SOURCE[0]}" "${userFile}' \
+  EXIT INT TERM SIGINT SIGQUIT ERR
 
 # Set IFS to preferred implementation
 IFS=$' \n\t'
 
 # Exit on error. Append '||true' when you run the script if you expect an error.
-set -o errexit
+#set -o errexit
+#set -o errtrace
 
 # Run in debug mode, if set
 if ${debug}; then set -x ; fi
 
 # Exit on empty variable
 if ${strict}; then set -o nounset ; fi
-
-# Exit the script if a command fails
-set -e
 
 # Run your script unless in 'source-only' mode
 if ! ${sourceOnly}; then _mainScript_; fi
