refactor script and add unit tests
- use versioned scripting functions
- using _uniqueFilename_ function
- unit tests added
- code cleanup

diff --git a/bin/convertVideo b/bin/convertVideo
--- a/bin/convertVideo
+++ b/bin/convertVideo
@@ -29,7 +29,7 @@ _mainScript_() {
     http -d --body http://www.sample-videos.com/video/mkv/720/big_buck_bunny_720p_1mb.mkv
     http -d --body http://www.sample-videos.com/audio/mp3/india-national-anthem.mp3
     http -d --body http://samples.mplayerhq.hu/avi/imaadpcm.avi
-    if type -P youtube-dl > /dev/null; then
+    if type -P youtube-dl &> /dev/null; then
       youtube-dl -f "[height <=? 720]" -o test-720p.mp4 https://www.youtube.com/watch?v=1-UdWS4RAA4
       youtube-dl -o test-1080p.mp4 https://www.youtube.com/watch?v=1-UdWS4RAA4
     fi
@@ -40,14 +40,6 @@ _mainScript_() {
 
   _errorHandling_() {
 
-    # Add homebrew and ~/bin to $PATH so the script can find executables
-    PATHS=(/usr/local/bin $HOME/bin);
-    for newPath in "${PATHS[@]}"; do
-      if ! echo "$PATH" | grep -Eq "(^|:)${newPath}($|:)" ; then
-        PATH="$newPath:$PATH"
-     fi
-    done
-
     # Check for the necessary command line packages
     verbose "Checking dependencies..."
     for CLIDependency in "${CLIDependencies[@]}"; do
@@ -56,30 +48,31 @@ _mainScript_() {
       fi
     done
 
-    # Confirm that ffprobe works
-    if ! ffprobe -v quiet -print_format json -show_format -show_streams "${args[0]}" &> /dev/null; then
-      die "Seems ffmpeg has a dependency problem"
-    fi
-
     # Confirm we have at least one video file. Add videos to ${filesToConvert[@]}
     verbose "Confirming we have video files to work on..."
     for file in "${args[@]}"; do
+      [ ! -f "$file" ] && continue
       local extension="${file##*.}" # Grab extension of file
       if _inArray_ "${extension,,}" "${videoTypes[@]}"; then
         filesToConvert+=("${file}")
       fi
     done
-    if [ ${#filesToConvert[@]} -eq 0 ]; then
-      die "Please specify at least one video file. Exiting."
+
+    [ ${#filesToConvert[@]} -eq 0 ] && die "Please specify at least one video file."
+
+
+   # Confirm that ffprobe works
+    if ! ffprobe -v quiet -print_format json -show_format -show_streams "${args[0]}" &> /dev/null; then
+      die "Seems ffmpeg has a dependency problem"
     fi
 
-    # Ensure a user sets an output format since we don't have a default.
+    # Ensure we have an output format.
     if [[ -z "${outputFormat}" ]]; then
       notice "No output format specified. Defaulting to 'mp4'"
       outputFormat="mp4"
     else # Confirm user specified output file is a video file
       if ! _inArray_ "${outputFormat}" "${videoTypes[@]}"; then
-        die "Specified output format '${outputFormat}' is not valid. Exiting."
+        die "Specified output format '${outputFormat}' is not valid."
       fi
     fi
   }
@@ -186,12 +179,12 @@ _mainScript_() {
       #Don't resize videos to their same size
       if [[ "${outputVideoSize}" =~ 720 ]]; then
         if [[ "$existingSize" == "720p" ]]; then
-          info "\t file already 720p. Will not resize to self."
+          info "File already 720p. Will not resize to self."
           return
         fi
       elif [[ "${outputVideoSize}" =~ 1080 ]]; then
         if [[ "$existingSize" == "1080p" ]]; then
-          info "\t file already 1080p. Will not resize to self."
+          info "File already 1080p. Will not resize to self."
           return
         fi
       fi
@@ -242,10 +235,8 @@ _mainScript_() {
         if ! _seekConfirmation_ "Upscale ${file} to ${outputVideoSize}? It is currently ${videoWidth}x${videoHeight}."; then return; fi
       fi
 
-
       # Finally, set the resize variable
       videoResize="-vf scale=${videoSize}" && verbose "\t videoResize:\t -vf scale=${outputVideoSize}"
-
 
       verbose "\t outputVideoSize:\t ${outputVideoSize}"
     }
@@ -265,30 +256,9 @@ _mainScript_() {
 
     # Don't convert to self if no other options set
     if [[ -z ${outputVideoSize} && "${outputFormat}" == "${file##*.}" && ! ${probe} ]]; then
-      warning "\t Can't convert a '${file##*.}' file to itself. Skipping..."
+      warning "Can't convert a '${file##*.}' file to itself. Skipping..."
       skipFile=true
     fi
-  }
-
-  _setOutputFile_() {
-    # _setOutputFile_() creates the name of new file to be generated by the conversion
-
-    outputDir=$(dirname "${file}")
-    baseFileName=$(basename "${file%.*}")
-    output="${baseFileName}.${outputFormat}"
-
-    if [ -e "${outputDir}/${output}" ]; then
-      # Increment file until it doesn't exist
-      num=2
-      while [[ -e "${outputDir}/${baseFileName} ${num}.${outputFormat}" ]]; do
-        (( num++ ))
-      done
-      output="${baseFileName} ${num}.${outputFormat}"
-    fi
-
-    # Add the output directory
-    output="${outputDir}/${output}"
-    verbose "\t newFileName:\t ${output}"
   }
 
   _doConvert_() {
@@ -305,7 +275,10 @@ _mainScript_() {
     # Respect the 'logfile' flag
     if ${printLog}; then ffmpegLog=">> ${logFile}"; fi
 
-    _execute_ "caffeinate -ism ffmpeg -i \"${file}\" ${videoResize} ${videoCommand} ${videoAudioCommand} ${audioConvertCommand} \"${output}\" ${ffquiet}"
+    # Set output file
+    output="$(_uniqueFileName_ "${file%.*}.${outputFormat}")"
+
+    _execute_ "caffeinate -ism ffmpeg -i \"${file}\" ${videoResize} ${videoCommand} ${videoAudioCommand} \"${output}\" ${ffquiet}"
 
     # Unset variables to get ready for the next file
       unset jsonFilename
@@ -335,10 +308,10 @@ _mainScript_() {
   for file in "${filesToConvert[@]}"; do
     skipFile=false
     info "Working on: $file"
+    file="$(_realpath_ "$file")"
     _parseFileJson_
     _setConversionVariables_
     if ${skipFile}; then continue; fi # Skip files if flagged
-    _setOutputFile_
     _doConvert_
     if ${deleteOriginal}; then _deleteOriginalFile_; fi
   done
@@ -360,14 +333,158 @@ _safeExit_() {
 }
 
 _inArray_() {
-  # Determine if a value is in an array.
-  # Usage: if _inArray_ "VALUE" "${ARRAY[@]}"; then ...
+  # v1.0.0
   local value="$1"; shift
   for arrayItem in "$@"; do
-    [[ "${arrayItem}" == "${value}" ]] && return 0
+      [[ "${arrayItem}" == "${value}" ]] && return 0
   done
   return 1
 }
+
+_execute_() {
+  # v1.0.0
+  if ${dryrun}; then
+    dryrun "${2:-$1}"
+  else
+    #set +e # don't exit script if execute fails
+    if $verbose; then
+      eval "$1"
+    else
+      eval "$1" &> /dev/null
+    fi
+    if [ $? -eq 0 ]; then
+      success "${2:-$1}"
+    else
+      warning "${2:-$1}"
+    fi
+    # set -e
+  fi
+}
+
+_seekConfirmation_() {
+  # v1.0.0
+  input "$@"
+  if "${force}"; then
+    verbose "Forcing confirmation with '--force' flag set"
+    return 0
+  else
+    while true; do
+      read -r -p " (y/n) " yn
+      case $yn in
+        [Yy]* ) return 0;;
+        [Nn]* ) return 1;;
+        * ) input "Please answer yes or no.";;
+      esac
+    done
+  fi
+}
+
+_realpath_() {
+  # v1.0.0
+  local success=true
+  local path="$1"
+
+  # make sure the string isn't empty as that implies something in further logic
+  if [ -z "$path" ]; then
+    success=false
+  else
+    # start with the file name (sans the trailing slash)
+    path="${path%/}"
+
+    # if we stripped off the trailing slash and were left with nothing, that means we're in the root directory
+    if [ -z "$path" ]; then
+      path="/"
+    fi
+
+    # get the basename of the file (ignoring '.' & '..', because they're really part of the path)
+    local file_basename="${path##*/}"
+    if [[ ( "$file_basename" = "." ) || ( "$file_basename" = ".." ) ]]; then
+      file_basename=""
+    fi
+
+    # extracts the directory component of the full path, if it's empty then assume '.' (the current working directory)
+    local directory="${path%$file_basename}"
+    if [ -z "$directory" ]; then
+      directory='.'
+    fi
+
+    # attempt to change to the directory
+    if ! cd "$directory" &>/dev/null ; then
+      success=false
+    fi
+
+    if $success; then
+      # does the filename exist?
+      if [[ ( -n "$file_basename" ) && ( ! -e "$file_basename" ) ]]; then
+        success=false
+      fi
+
+      # get the absolute path of the current directory & change back to previous directory
+      local abs_path
+      abs_path="$(pwd -P)"
+      cd "-" &>/dev/null || return
+
+      # Append base filename to absolute path
+      if [ "${abs_path}" = "/" ]; then
+        abs_path="${abs_path}${file_basename}"
+      else
+        abs_path="${abs_path}/${file_basename}"
+      fi
+
+      # output the absolute path
+      echo "$abs_path"
+    fi
+  fi
+
+  $success
+}
+
+_uniqueFileName_() {
+  # v2.0.0
+  local fullfile="${1:?_uniqueFileName_ needs a file}"
+  local spacer="${2:- }"
+  local directory
+  local filename
+
+  # Find directories with _realpath_ if available
+  if [ -e "$fullfile" ]; then
+    if type -t _realpath_ | grep -E '^function$' &>/dev/null; then
+      fullfile="$(_realpath_ "$fullfile")"
+    fi
+  fi
+
+  directory="$(dirname "$fullfile")"
+  filename="$(basename "$fullfile")"
+
+  # Extract extensions only when they exist
+  if [[ "$filename" =~ \.[a-zA-Z]{2,3}$ ]]; then
+    local extension=".${filename##*.}"
+    local filename="${filename%.*}"
+  fi
+
+  local newfile="${directory}/${filename}${extension}"
+
+  if [ -e "${newfile}" ]; then
+    local n=2
+    while [[ -e "${directory}/${filename}${spacer}${n}${extension}" ]]; do
+      (( n++ ))
+    done
+    newfile="${directory}/${filename}${spacer}${n}${extension}"
+  fi
+
+  echo "${newfile}"
+}
+
+_setPATH_() {
+  # setPATH() Add homebrew and ~/bin to $PATH so the script can find executables
+  PATHS=(/usr/local/bin ${HOME}/bin);
+  for newPath in "${PATHS[@]}"; do
+    if ! echo "$PATH" | grep -Eq "(^|:)${newPath}($|:)" ; then
+      PATH="${newPath}:${PATH}"
+   fi
+ done
+}
+_setPATH_
 
 # Set Base Variables
 # ----------------------
@@ -376,7 +493,7 @@ scriptName=$(basename "$0")
 # Set Flags
 quiet=false;              printLog=false;               verbose=false;
 force=false;              strict=false;                 dryrun=false;
-debug=false;              args=();
+debug=false;              sourceOnly=false;             args=();
 
 deleteOriginal=false;     dryrun=false;                testFiles=false;
 probe=false;
@@ -409,8 +526,6 @@ ${bold}File Options:${reset}
   -o, --output      Specify the output format for the file(s) to be converted to.
                     ('mkv', 'mp4', 'm4a'). If not specified, default is 'mp4'.
   --delete          Delete the original file after conversion.
-  --saveDir         Specify a folder for the converted files to be saved to.  Defaults to
-                    the directory the script is invoked in.
 
  ${bold}Options:${reset}
   --testFiles       Download test media files for use in debugging
@@ -434,6 +549,7 @@ ${bold}File Options:${reset}
 }
 
 _alert_() {
+  # v1.0.0
   if [ "${1}" = "error" ]; then local color="${bold}${red}"; fi
   if [ "${1}" = "warning" ]; then local color="${red}"; fi
   if [ "${1}" = "success" ]; then local color="${green}"; fi
@@ -446,7 +562,7 @@ _alert_() {
   if [[ "${TERM}" != "xterm"* ]] || [ -t 1 ]; then color=""; reset=""; fi
 
   # Print to console when script is not 'quiet'
-  if ${quiet}; then return; else
+  if ${quiet}; then tput cuu1 ; return; else # tput cuu1 moves cursor up one line
    echo -e "$(date +"%r") ${color}$(printf "[%7s]" "${1}") ${_message}${reset}";
   fi
 
@@ -513,73 +629,27 @@ unset options
 # Read the options and set stuff
 while [[ $1 = -?* ]]; do
   case $1 in
-    --testFiles) testFiles=true ;;
-    -o|--output) shift; outputFormat="${1,,}" ;;
-    --probe) probe=true; dryrun=true ;;
-    --size) shift; outputVideoSize="$1" ;;
-    -n|--dryrun) dryrun=true ;;
-    --delete) deleteOriginal=true ;;
 
+    -o|--output) shift; outputFormat="${1,,}" ;;
+    -n|--dryrun) dryrun=true ;;
     -h|--help) _usage_ >&2; _safeExit_ ;;
-    --version) echo "$(basename $0) ${version}"; _safeExit_ ;;
     -v|--verbose) verbose=true ;;
     -l|--log) printLog=true ;;
     -q|--quiet) quiet=true ;;
     -s|--strict) strict=true;;
     -d|--debug) debug=true;;
+    --probe) probe=true; dryrun=true ;;
+    --size) shift; outputVideoSize="$1" ;;
+    --testFiles) testFiles=true ;;
+    --delete) deleteOriginal=true ;;
+    --version) echo "$(basename $0) ${version}"; _safeExit_ ;;
+    --source-only) sourceOnly=true;;
     --force) force=true ;;
     --endopts) shift; break ;;
     *) die "invalid option: '$1'." ;;
   esac
   shift
 done
-
-_seekConfirmation_() {
-  # Seeks a Yes or No answer to a question.  Usage:
-  #   if _seekConfirmation_ "Answer this question"; then
-  #     something
-  #   fi
-  input "$@"
-  if "${force}"; then
-    verbose "Forcing confirmation with '--force' flag set"
-    return 0
-  else
-    while true; do
-      read -r -p " (y/n) " yn
-      case $yn in
-        [Yy]* ) return 0;;
-        [Nn]* ) return 1;;
-        * ) input "Please answer yes or no.";;
-      esac
-    done
-  fi
-}
-
-_execute_() {
-  # _execute_ - wrap an external command in '_execute_' to push native output to /dev/null
-  #           and have control over the display of the results.  In "dryrun" mode these
-  #           commands are not executed at all. In Verbose mode, the commands are executed
-  #           with results printed to stderr and stdin
-  #
-  # usage:
-  #   _execute_ "cp -R somefile.txt someNewFile.txt" "Optional message to print to user"
-  if ${dryrun}; then
-    dryrun "${2:-$1}"
-  else
-    #set +e # don't exit script if execute fails
-    if $verbose; then
-      eval "$1"
-    else
-      eval "$1" &> /dev/null
-    fi
-    if [ $? -eq 0 ]; then
-      success "${2:-$1}"
-    else
-      warning "${2:-$1}"
-    fi
-    # set -e
-  fi
-}
 
 # Store the remaining part as arguments.
 args+=("$@")
@@ -603,8 +673,8 @@ if ${strict}; then set -o nounset ; fi
 # This way you can catch the error in case mysqldump fails in `mysqldump |gzip`, for example.
 set -o pipefail
 
-# Run your script
-_mainScript_
+# Run your script unless in 'source-only' mode
+if ! ${sourceOnly}; then _mainScript_; fi
 
 # Exit cleanly
-_safeExit_
+if ! ${sourceOnly}; then _safeExit_; fi
