Use local trash script

diff --git a/bin/trash b/bin/trash
--- a/bin/trash
+++ b/bin/trash
@@ -153,10 +153,8 @@ quiet=false
 printLog=false
 logErrors=true
 verbose=false
-strict=false
 dryrun=false
 sourceOnly=false
-debug=false
 args=()
 
 list=false
@@ -167,125 +165,109 @@ systemRM=false
 # Options and Usage
 # -----------------------------------
 _usage_() {
-  echo -n "$(basename "$0") [OPTION]... [FILE]...
+  cat <<EOF
+  $(basename "$0") [OPTION]... [FILE]...
 
- ${bold}Trash${reset} allows MacOS trashing of files instead of tempting fate with ${bold}rm${reset}.
- Anything deleted with Trash will be moved to the native MacOS trash folder.
+  ${bold}Trash${reset} allows MacOS trashing of files instead of tempting fate with ${bold}rm${reset}.
+  Anything deleted with Trash will be moved to the native MacOS trash folder.
 
- This script:
+  This script:
 
-  - Correctly handles ${bold}trashing files on other volumes${reset}
-  - Uses the ${bold}same filename renaming scheme as Finder${reset} for duplicate file names
-  - Can ${bold}list trash contents${reset} w/disk usage summary
-  - ${bold}Empty trash${reset}.
-  - Does not require Finder to be running.
+    - Correctly handles ${bold}trashing files on other volumes${reset}
+    - Uses the ${bold}same filename renaming scheme as Finder${reset} for duplicate file names
+    - Can ${bold}list trash contents${reset} w/disk usage summary
+    - ${bold}Empty trash${reset}.
+    - Does not require Finder to be running.
 
- ${bold}Options:${reset}
-  -l , --list         List trash contents
-  -L, --noErrorLog    Print log level error and fatal to a log (default 'true')
-  -e, --empty         Empty trash contents
-  -n, --dryrun        Non-destructive run.
-  -s, --system        Forces native Unix 'rm' command
-  --bypassFinder      Bypasses AppleScript. Runs pure unix commands.
-  --log               Print log to file
-  -q, --quiet         Quiet (no output)
-  -v, --verbose       Output more information. (Items echoed to 'verbose')
-  -d, --debug         Runs script in BASH debug mode (set -x)
-  -h, --help          Display this help and exit
-"
+  ${bold}Options:${reset}
+    -l , --list         List trash contents
+    -L, --noErrorLog    Print log level error and fatal to a log (default 'true')
+    -e, --empty         Empty trash contents
+    -n, --dryrun        Non-destructive run.
+    -s, --system        Forces native Unix 'rm' command
+    -q, --quiet         Quiet (no output)
+    -v, --verbose       Output more information. (Items echoed to 'verbose')
+    -h, --help          Display this help and exit
+    --bypassFinder      Bypasses AppleScript. Runs pure unix commands.
+    --log               Print log to file
+EOF
 }
 
-# Iterate over options breaking -ab into -a -b when needed and --foo=bar into
-# --foo bar
-optstring=h
-unset options
-while (($#)); do
-  case $1 in
-    # If option is of type -ab
-    -[!-]?*)
-      # Loop over each character starting with the second
-      for ((i = 1; i < ${#1}; i++)); do
-        c=${1:i:1}
+_parseOptions_() {
+  # Iterate over options
+  # breaking -ab into -a -b when needed and --foo=bar into --foo bar
+  optstring=h
+  unset options
+  while (($#)); do
+    case $1 in
+      # If option is of type -ab
+      -[!-]?*)
+        # Loop over each character starting with the second
+        for ((i = 1; i < ${#1}; i++)); do
+          c=${1:i:1}
+          options+=("-$c") # Add current char to options
+          # If option takes a required argument, and it's not the last char make
+          # the rest of the string its argument
+          if [[ $optstring == *"$c:"* && ${1:i+1} ]]; then
+            options+=("${1:i+1}")
+            break
+          fi
+        done
+        ;;
+      # If option is of type --foo=bar
+      --?*=*) options+=("${1%%=*}" "${1#*=}") ;;
+      # add --endopts for --
+      --) options+=(--endopts) ;;
+      # Otherwise, nothing special
+      *) options+=("$1") ;;
+    esac
+    shift
+  done
+  set -- "${options[@]}"
+  unset options
 
-        # Add current char to options
-        options+=("-$c")
-
-        # If option takes a required argument, and it's not the last char make
-        # the rest of the string its argument
-        if [[ $optstring == *"$c:"* && ${1:i+1} ]]; then
-          options+=("${1:i+1}")
-          break
-        fi
-      done
-      ;;
-
-    # If option is of type --foo=bar
-    --?*=*) options+=("${1%%=*}" "${1#*=}") ;;
-    # add --endopts for --
-    --) options+=(--endopts) ;;
-    # Otherwise, nothing special
-    *) options+=("$1") ;;
-  esac
-  shift
-done
-set -- "${options[@]}"
-unset options
-
-# Print help if no arguments were passed.
-# Uncomment to force arguments when invoking the script
-# -------------------------------------
-[[ $# -eq 0 ]] && set -- "--help"
-
-# Read the options and set stuff
-while [[ $1 == -?* ]]; do
-  case $1 in
-    -h | --help)
-      _usage_ >&2
-      _safeExit_
-      ;;
-    --bypassFinder) bypassFinder=true ;;
+  # Read the options and set stuff
+  while [[ $1 == -?* ]]; do
+    case $1 in
+      -h | --help)
+        _usage_ >&2
+        _safeExit_
+        ;;
+--bypassFinder) bypassFinder=true ;;
     -s | --system) systemRM=true ;;
-    -L | --noErrorLog) logErrors=false ;;
     -l | --list) list=true ;;
     -e | --empty) emptyTrash=true ;;
-    -n | --dryrun) dryrun=true ;;
-    -v | --verbose) verbose=true ;;
-    --log) printLog=true ;;
-    -q | --quiet) quiet=true ;;
-    -S | --strict) strict=true ;;
-    -d | --debug) debug=true ;;
-    --source-only) sourceOnly=true ;;
-    --endopts)
-      shift
-      break
-      ;;
-    *) die "invalid option: '$1'." ;;
-  esac
-  shift
-done
+      -L | --noErrorLog) logErrors=false ;;
+      -n | --dryrun) dryrun=true ;;
+      -v | --verbose) verbose=true ;;
+      --log) printLog=true ;;
+      -q | --quiet) quiet=true ;;
+      --source-only) sourceOnly=true ;;
+      --force) force=true ;;
+      --endopts)
+        shift
+        break
+        ;;
+      *) die "invalid option: '$1'." ;;
+    esac
+    shift
+  done
+  args+=("$@") # Store the remaining user input as arguments.
+}
+_parseOptions_ "$@"
 
-# Store the remaining part as arguments.
-args+=("$@")
-
-# Trap bad exits with your cleanup function
-trap '_trapCleanup_ $LINENO $BASH_LINENO "$BASH_COMMAND" "${FUNCNAME[*]}" "$0" "${BASH_SOURCE[0]}" "${userFile}' \
-  EXIT INT TERM SIGINT SIGQUIT ERR
-
-# Set IFS to preferred implementation
-IFS=$' \n\t'
-
-# Exit on error. Append '||true' when you run the script if you expect an error.
-set -o errexit
-set -o errtrace
-
-# Run in debug mode, if set
-if ${debug}; then set -x; fi
-
-# Exit on empty variable
-if ${strict}; then set -o nounset; fi
-
-# Run your script unless in 'source-only' mode
-if ! ${sourceOnly}; then _mainScript_; fi
-
-# Exit cleanly
-if ! ${sourceOnly}; then _safeExit_; fi
+# Initialize and run the script
+trap '_trapCleanup_ $LINENO $BASH_LINENO "$BASH_COMMAND" "${FUNCNAME[*]}" "$0" "${BASH_SOURCE[0]}"' \
+  EXIT INT TERM SIGINT SIGQUIT
+set -o errtrace                           # Trap errors in subshells and functions
+set -o errexit                            # Exit on error. Append '||true' if you expect an error
+set -o pipefail                           # Use last non-zero exit code in a pipeline
+shopt -s nullglob globstar                # Make `for f in *.txt` work when `*.txt` matches zero files
+IFS=$' \n\t'                              # Set IFS to preferred implementation
+# set -o xtrace                           # Uncomment to run in debug mode
+set -o nounset                            # Disallow expansion of unset variables
+[[ $# -eq 0 ]] && _parseOptions_ "-h"     # Uncomment to force arguments when invoking the script
+# _makeTempDir_ "$(basename "$0")"        # Uncomment to create a temp directory '$tmpDir'
+# _acquireScriptLock_                     # Uncomment to acquire script lock
+if ! ${sourceOnly}; then _mainScript_; fi # Run script unless in 'source-only' mode
+if ! ${sourceOnly}; then _safeExit_; fi   # Exit cleanly
