use new script template format

diff --git a/bin/updateHomebrew b/bin/updateHomebrew
--- a/bin/updateHomebrew
+++ b/bin/updateHomebrew
@@ -1,7 +1,5 @@
 #!/usr/bin/env bash
 
-version="1.0.0"
-
 _mainScript_() {
 
   [[ "$OSTYPE" != "darwin"* ]] \
@@ -76,7 +74,7 @@ _mainScript_() {
       i=1
     fi
     if [[ $i -eq 1 ]] && _seekConfirmation_ "Overwrite Brewfile with these changes"; then
-      _execute_ "cp \"$t\" \"$brewfile\"" "Writing changes to '$brewfile'"\
+      _execute_ "cp \"$t\" \"$brewfile\"" "Writing changes to '$brewfile'" \
         || error "Could not overwrite '$brewfile'" "$LINENO"
     else
       info "No changes to Brewfile"
@@ -114,24 +112,18 @@ printLog=false
 logErrors=true
 verbose=false
 force=false
-strict=false
 dryrun=false
-debug=false
 sourceOnly=false
 args=()
-
-# Set Temp Directory
-tmpDir="${TMPDIR:-/tmp/}$(basename "$0").$RANDOM.$RANDOM.$RANDOM.$$"
-(umask 077 && mkdir "${tmpDir}") || {
-  fatal "Could not create temporary directory! Exiting." "$LINENO"
-}
 
 # Options and Usage
 # -----------------------------------
 _usage_() {
-  echo -n "${scriptName} [OPTION]... [FILE]...
+  cat <<EOF
 
-This script upgrades  Mac OS applications managed by Homebrew Cask
+  $(basename "$0") [OPTION]...
+
+  This script upgrades Mac OS applications managed by Homebrew Cask
 
  ${bold}Option Flags:${reset}
 
@@ -139,114 +131,85 @@ This script upgrades  Mac OS applications managed by Homebrew Cask
   -l, --log         Print log to file
   -n, --dryrun      Non-destructive. Makes no permanent changes.
   -q, --quiet       Quiet (no output)
-  -s, --strict      Exit script with null variables.  i.e 'set -o nounset'
   -v, --verbose     Output more information. (Items echoed to 'verbose')
-  -d, --debug       Runs script in BASH debug mode (set -x)
   -h, --help        Display this help and exit
       --version     Output version information and exit
       --source-only Bypasses main script functionality to allow unit tests of functions
       --force       Skip all user interaction.  Implied 'Yes' to all actions.
-"
+EOF
 }
 
-# Iterate over options breaking -ab into -a -b when needed and --foo=bar into
-# --foo bar
-optstring=h
-unset options
-while (($#)); do
-  case $1 in
-    # If option is of type -ab
-    -[!-]?*)
-      # Loop over each character starting with the second
-      for ((i = 1; i < ${#1}; i++)); do
-        c=${1:i:1}
+_parseOptions_() {
+  # Iterate over options
+  # breaking -ab into -a -b when needed and --foo=bar into --foo bar
+  optstring=h
+  unset options
+  while (($#)); do
+    case $1 in
+      # If option is of type -ab
+      -[!-]?*)
+        # Loop over each character starting with the second
+        for ((i = 1; i < ${#1}; i++)); do
+          c=${1:i:1}
+          options+=("-$c") # Add current char to options
+          # If option takes a required argument, and it's not the last char make
+          # the rest of the string its argument
+          if [[ $optstring == *"$c:"* && ${1:i+1} ]]; then
+            options+=("${1:i+1}")
+            break
+          fi
+        done
+        ;;
+      # If option is of type --foo=bar
+      --?*=*) options+=("${1%%=*}" "${1#*=}") ;;
+      # add --endopts for --
+      --) options+=(--endopts) ;;
+      # Otherwise, nothing special
+      *) options+=("$1") ;;
+    esac
+    shift
+  done
+  set -- "${options[@]}"
+  unset options
 
-        # Add current char to options
-        options+=("-$c")
+  # Read the options and set stuff
+  while [[ $1 == -?* ]]; do
+    case $1 in
+      -h | --help)
+        _usage_ >&2
+        _safeExit_
+        ;;
+      -L | --noErrorLog) logErrors=false ;;
+      -n | --dryrun) dryrun=true ;;
+      -v | --verbose) verbose=true ;;
+      -l | --log) printLog=true ;;
+      -q | --quiet) quiet=true ;;
+      --source-only) sourceOnly=true ;;
+      --force) force=true ;;
+      --endopts)
+        shift
+        break
+        ;;
+      *) die "invalid option: '$1'." ;;
+    esac
+    shift
+  done
+  args+=("$@") # Store the remaining user input as arguments.
+}
+_parseOptions_ "$@"
 
-        # If option takes a required argument, and it's not the last char make
-        # the rest of the string its argument
-        if [[ $optstring == *"$c:"* && ${1:i+1} ]]; then
-          options+=("${1:i+1}")
-          break
-        fi
-      done
-      ;;
-
-    # If option is of type --foo=bar
-    --?*=*) options+=("${1%%=*}" "${1#*=}") ;;
-    # add --endopts for --
-    --) options+=(--endopts) ;;
-    # Otherwise, nothing special
-    *) options+=("$1") ;;
-  esac
-  shift
-done
-set -- "${options[@]}"
-unset options
-
-# Print help if no arguments were passed.
-# Uncomment to force arguments when invoking the script
-# -------------------------------------
-# [[ $# -eq 0 ]] && set -- "--help"
-
-# Read the options and set stuff
-while [[ $1 == -?* ]]; do
-  case $1 in
-    -h | --help)
-      _usage_ >&2
-      _safeExit_
-      ;;
-    -L | --noErrorLog) logErrors=false ;;
-    -n | --dryrun) dryrun=true ;;
-    -v | --verbose) verbose=true ;;
-    -l | --log) printLog=true ;;
-    -q | --quiet) quiet=true ;;
-    -s | --strict) strict=true ;;
-    -d | --debug) debug=true ;;
-    --version)
-      echo "$(basename $0) ${version}"
-      _safeExit_
-      ;;
-    --source-only) sourceOnly=true ;;
-    --force) force=true ;;
-    --endopts)
-      shift
-      break
-      ;;
-    *)
-      echo "invalid option: '$1'."
-      exit 1
-      ;;
-  esac
-  shift
-done
-
-# Store the remaining part as arguments.
-args+=("$@")
-
-# Trap bad exits with your cleanup function
+# Initialize and run the script
 trap '_trapCleanup_ $LINENO $BASH_LINENO "$BASH_COMMAND" "${FUNCNAME[*]}" "$0" "${BASH_SOURCE[0]}"' \
   EXIT INT TERM SIGINT SIGQUIT
-
-# Set IFS to preferred implementation
-IFS=$' \n\t'
-
-# Exit on error. Append '||true' when you run the script if you expect an error.
-set -o errtrace
-set -o errexit
-
-# Force pipelines to fail on the first non-zero status code.
-set -o pipefail
-
-# Run in debug mode, if set
-if ${debug}; then set -x; fi
-
-# Exit on empty variable
-if ${strict}; then set -o nounset; fi
-
-# Run your script unless in 'source-only' mode
-if ! ${sourceOnly}; then _mainScript_; fi
-
-# Exit cleanly
-if ! ${sourceOnly}; then _safeExit_; fi
+set -o errtrace                           # Trap errors in subshells and functions
+set -o errexit                            # Exit on error. Append '||true' if you expect an error
+set -o pipefail                           # Use last non-zero exit code in a pipeline
+shopt -s nullglob globstar                # Make `for f in *.txt` work when `*.txt` matches zero files
+IFS=$' \n\t'                              # Set IFS to preferred implementation
+# set -o xtrace                           # Uncomment to run in debug mode
+set -o nounset                            # Disallow expansion of unset variables
+# [[ $# -eq 0 ]] && _parseOptions_ "-h"   # Uncomment to force arguments when invoking the script
+ _makeTempDir_ "$(basename "$0")"         # Uncomment to create a temp directory '$tmpDir'
+_acquireScriptLock_                       # Uncomment to acquire script lock
+if ! ${sourceOnly}; then _mainScript_; fi # Run script unless in 'source-only' mode
+if ! ${sourceOnly}; then _safeExit_; fi   # Exit cleanly
