Update package managers
- Use ASDF for ruby & nodejs
- Add a Brewfile
- Rewrite script to keep homebrew updated
- - Writes changes to Brewfile
- - Refactor code
- Remove unneeded files

diff --git a/bin/updateHomebrew b/bin/updateHomebrew
--- a/bin/updateHomebrew
+++ b/bin/updateHomebrew
@@ -7,10 +7,14 @@ _mainScript_() {
   [[ "$OSTYPE" != "darwin"* ]] \
     && fatal "We are not on macOS" "$LINENO"
 
-  if ! command -v brew &>/dev/null; then fatal "Can not continue wthout homebrew"; fi
-    
-  _upgradeCasks_() {
+  if ! command -v brew &>/dev/null; then fatal "Can not continue wthout homebrew" "$LINENO"; fi
 
+  info "Updating Homebrew..."
+  _execute_ -vp "brew update"
+  _execute_ -vp "brew upgrade"
+
+  _upgradeCasks_() {
+    info "Updating casks ..."
     local cask casks
 
     # Sometimes license files can get old and cause 'brew cask' to throw errors.  This can help
@@ -22,9 +26,8 @@ _mainScript_() {
       #_execute_ "brew cask reinstall $cask"
     done < <(grep -ilr --include \*.rb license $(brew --prefix)/Caskroom/*/.metadata | awk -F '/' '{print $5}' | sort -u)
 
-
-  # Now we update casks
-  if [ "$(brew cask outdated --greedy --verbose | awk '$4 != "latest" {print $1}')" ]; then
+    # Now we update casks
+    if [ "$(brew cask outdated --greedy --verbose | awk '$4 != "latest" {print $1}')" ]; then
       while read -r c; do
         version=$(brew cask info $c | sed -n "s/$c:\ \(.*\)/\1/p")
         installed=$(find "/usr/local/Caskroom/$c" -type d -maxdepth 1 -maxdepth 1 -name "$c")
@@ -43,6 +46,45 @@ _mainScript_() {
     fi
   }
   _upgradeCasks_
+
+  info "Cleaning Up..."
+  _execute_ -vp "brew cleanup"
+  _execute_ -vp "brew cask cleanup"
+  _execute_ -vp "brew prune"
+
+  _updateBrewfile_() {
+    local t="$(mktemp "${tmpDir}/XXXXXXXXXXXXX")"
+    local i=0
+    local brewfile="${HOME}/dotfiles/config/shell/Brewfile"
+
+    [ -f "$brewfile" ] \
+      || {
+        error "Can not find brewfile" "$LINENO"
+        return 0
+      }
+
+    # Write temp brewfile
+    brew bundle dump --file="$t" --force
+
+    info "Checking Brewfile ..."
+    if [[ $(comm -2 -3 --nocheck-order "$t" "$brewfile") != "" ]]; then
+      notice "These lines will be added to Brewfile"
+      comm -2 -3 --nocheck-order <(sort "$t") <(sort "$brewfile")
+      i=1
+    fi
+    if [[ $(comm -1 -3 --nocheck-order "$t" "$brewfile") != "" ]]; then
+      notice "These lines will be removed"
+      comm -1 -3 --nocheck-order <(sort "$t") <(sort "$brewfile")
+      i=1
+    fi
+    if [[ $i -eq 1 ]] && _seekConfirmation_ "Overwrite Brewfile with these changes"; then
+      _execute_ "cp \"$t\" \"$brewfile\"" "Writing changes to '$brewfile'"\
+        || error "Could not overwrite '$brewfile'" "$LINENO"
+    else
+      notice "No changes to Brewfile"
+    fi
+  }
+  _updateBrewfile_
 
 } # end _mainScript_
 
@@ -79,6 +121,12 @@ dryrun=false
 debug=false
 sourceOnly=false
 args=()
+
+# Set Temp Directory
+tmpDir="${TMPDIR:-/tmp/}$(basename "$0").$RANDOM.$RANDOM.$RANDOM.$$"
+(umask 077 && mkdir "${tmpDir}") || {
+  fatal "Could not create temporary directory! Exiting." "$LINENO"
+}
 
 # Options and Usage
 # -----------------------------------
@@ -168,7 +216,10 @@ while [[ $1 == -?* ]]; do
       shift
       break
       ;;
-    *) die "invalid option: '$1'." ;;
+    *)
+      echo "invalid option: '$1'."
+      exit 1
+      ;;
   esac
   shift
 done
