fix: harden install-non-pkg-mngr script (#25)

diff --git a/dotfiles/.chezmoiscripts/run_after_30_install-non-pkg-mngr-binaries.sh.tmpl b/dotfiles/.chezmoiscripts/run_after_30_install-non-pkg-mngr-binaries.sh.tmpl
--- a/dotfiles/.chezmoiscripts/run_after_30_install-non-pkg-mngr-binaries.sh.tmpl
+++ b/dotfiles/.chezmoiscripts/run_after_30_install-non-pkg-mngr-binaries.sh.tmpl
@@ -53,8 +53,9 @@ if [[ ! -e "${HOME}/bin/install-binary.py" ]]; then
     _safeExit_
 fi
 
-
-uv run -q ${HOME}/bin/install-binary.py --binary-name="{{ $binary.name }}" --repository="{{ $binary.repository }}" --version-regex="{{ $binary.version_regex }}" --remove-from-release="{{ $binary.remove_from_release }}" --executable-name="{{ $binary.executable_name }}" --description="{{ $binary.description }}"
+if ! uv run -q ${HOME}/bin/install-binary.py --binary-name="{{ $binary.name }}" --repository="{{ $binary.repository }}" --version-regex="{{ $binary.version_regex }}" --remove-from-release="{{ $binary.remove_from_release }}" --executable-name="{{ $binary.executable_name }}" --description="{{ $binary.description }}"; then
+    error "Could not install {{ $binary.name }}. Review error messages above."
+fi
 
 
 {{ end }}
