feat(macos): run macos config script (#11)

diff --git a/dotfiles/.chezmoiscripts/run_before_install-atuin.sh.tmpl b/dotfiles/.chezmoiscripts/run_before_install-atuin.sh.tmpl
--- a/dotfiles/.chezmoiscripts/run_before_install-atuin.sh.tmpl
+++ b/dotfiles/.chezmoiscripts/run_before_install-atuin.sh.tmpl
@@ -1,14 +1,18 @@
 #!/usr/bin/env bash
 
+{{ template "shared_script_utils.bash" }}
+
 # This script installs the Atuin binary for better history browsing
 # https://docs.atuin.sh/
 
 # check for unzip before we continue
 if [ ! "$(command -v curl)" ]; then
-    echo 'curl is required but was not found. Install curl first and then run this script again.' >&2
-    exit 1
+    error 'curl is required but was not found. Install curl first and then run this script again.' >&2
+    _safeExit_ 1
 fi
 
 if [ ! "$(command -v unzip)" ]; then
     curl --proto '=https' --tlsv1.2 -sSf https://setup.atuin.sh | bash
 fi
+
+_safeExit_
