ci: fix workflow

diff --git a/.github/workflows/automated_tests.yml b/.github/workflows/automated_tests.yml
--- a/.github/workflows/automated_tests.yml
+++ b/.github/workflows/automated_tests.yml
@@ -27,40 +27,41 @@ concurrency:
 
 jobs:
     test-dotfiles:
-        runs-on: ubuntu-latest
+        # runs-on: ubuntu-latest
         strategy:
             fail-fast: true
             matrix:
-                include:
-                    - name: ubuntu
-                      os: ubuntu-latest
-                    - name: macOS
-                      os: macos-latest
+                os: ["ubuntu-latest", "macos-latest"]
+        runs-on: ${{ matrix.os }}
         steps:
-            - name: Install APT dependencies
-              if: matrix.name == 'ubuntu'
-              run: |
-                  sudo apt-get install -y git build-essential
+            # - name: Install APT dependencies
+            #   if: matrix.name == 'ubuntu'
+            #   run: |
+            #       apt-get update
+            #       apt-get install -y git zsh
 
             # ----------------------------------------------
             #    Checkout repository
             # ----------------------------------------------
             - name: Checkout repository
               uses: actions/checkout@v4
-              with:
-                  path: .local/share/chezmoi
+
+            - name: Copy repository to /root/
+              run: |
+                  mkdir -p /root/.local/share/chezmoi
+                  cp -a . /root/.local/share/chezmoi
 
             # ----------------------------------------------
             # Create config file
             # ----------------------------------------------
             - name: Create config file
               run: |
-                  mkdir -p .config/chezmoi
-                  echo '[data]' > .config/chezmoi/chezmoi.toml
-                  echo '    email        = "test@test.com"' >> .config/chezmoi/chezmoi.toml
-                  echo '    github_user  = "natelandau"' >> .config/chezmoi/chezmoi.toml
-                  echo '    home_network = false' >> .config/chezmoi/chezmoi.toml
-                  echo '    use_secrets  = false' >> .config/chezmoi/chezmoi.toml
+                  mkdir -p /root/.config/chezmoi
+                  echo '[data]' > /root/.config/chezmoi/chezmoi.toml
+                  echo '    email        = "test@test.com"' >> /root/.config/chezmoi/chezmoi.toml
+                  echo '    github_user  = "natelandau"' >> /root/.config/chezmoi/chezmoi.toml
+                  echo '    home_network = false' >> /root/.config/chezmoi/chezmoi.toml
+                  echo '    use_secrets  = false' >> /root/.config/chezmoi/chezmoi.toml
 
             # ----------------------------------------------
             # Install chezmoi
@@ -74,14 +75,58 @@ jobs:
             # ----------------------------------------------
             - name: Run chezmoi apply
               run: |
-                  chezmoi apply --verbose
+                  ./bin/chezmoi apply
 
             # ----------------------------------------------
-            # Confirm dotfiles are installed
+            # UBUNTU: Confirm dotfiles are installed
             # ----------------------------------------------
             - name: Confirm dotfiles are installed
+              if: startsWith(matrix.os, 'ubuntu')
               run: |
-                  echo "------ ls -la ~ ------"
-                  ls -la ~
-                  echo "------ ls -la ~/.shell ------"
-                  ls -la ~/.shell
+                  echo "------- Testing files -------"
+                  cd /root
+                  # echo "pwd: $(pwd)"
+                  # ls -al
+
+                  # Confirm files exist
+                  for file in .zshrc .bashrc .gitconfig .shell .ssh/config .shell/050-linux.sh; do
+                    if [ ! -e $file ]; then
+                        echo "$file not found"
+                        exit 1
+                    fi
+                  done
+
+                  # Confirm files don't exist
+                  for file in Library .shell/050-macos.sh; do
+                    if [ -e $file ]; then
+                        echo "$file found"
+                        exit 1
+                    fi
+                  done
+
+            # ----------------------------------------------
+            # MACOS: Confirm dotfiles are installed
+            # ----------------------------------------------
+            - name: Confirm dotfiles are installed
+              if: startsWith(matrix.os, 'macos')
+              run: |
+                  echo "------- Testing files -------"
+                  cd /root
+                  # echo "pwd: $(pwd)"
+                  # ls -al
+
+                  # Confirm files exist
+                  for file in .zshrc .bashrc .gitconfig .shell .ssh/config Library .shell/050-macos.sh; do
+                    if [ ! -e $file ]; then
+                        echo "$file not found"
+                        exit 1
+                    fi
+                  done
+
+                  # Confirm files don't exist
+                  for file in Library .shell/050-linux.sh; do
+                    if [ -e $file ]; then
+                        echo "$file found"
+                        exit 1
+                    fi
+                  done
